from dataclasses import dataclass
from typing import Optional, Dict

from BaseClasses import Item, ItemClassification
from .Names import ItemName

base_item_id: int = 400000


class LB1Item(Item):
    game: str = "Lego Batman The Video Game"


@dataclass
class LB1ItemData:
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.filler
    type: str = "Minikit"
    count: int = 1


character_item_table: Dict[str, LB1ItemData] = {
    # ItemName.batman_unlocked: LB1ItemData(base_item_id + 0, ItemClassification.progression, "Character"),
    # ItemName.robin_unlocked: LB1ItemData(base_item_id + 1, ItemClassification.progression, "Character"),
    ItemName.brucewayne_unlocked: LB1ItemData(base_item_id + 2, ItemClassification.filler, "Character"),
    ItemName.alfred_unlocked: LB1ItemData(base_item_id + 3, ItemClassification.filler, "Character"),
    ItemName.batgirl_unlocked: LB1ItemData(base_item_id + 4, ItemClassification.progression_deprioritized, "Character"),
    ItemName.nightwing_unlocked: LB1ItemData(base_item_id + 5,
                                             ItemClassification.progression_deprioritized, "Character"),
    ItemName.commissionergordon_unlocked: LB1ItemData(base_item_id + 6, ItemClassification.filler, "Character"),
    ItemName.policeofficer_unlocked: LB1ItemData(base_item_id + 7, ItemClassification.filler, "Character"),
    ItemName.fishmonger_unlocked: LB1ItemData(base_item_id + 8, ItemClassification.filler, "Character"),
    ItemName.militarypoliceman_unlocked: LB1ItemData(base_item_id + 9, ItemClassification.filler, "Character"),
    ItemName.securityguard_unlocked: LB1ItemData(base_item_id + 10, ItemClassification.filler, "Character"),
    ItemName.swat_unlocked: LB1ItemData(base_item_id + 11, ItemClassification.filler, "Character"),
    ItemName.scientist_unlocked: LB1ItemData(base_item_id + 12,
                                             ItemClassification.progression_deprioritized, "Character"),
    ItemName.sailor_unlocked: LB1ItemData(base_item_id + 13, ItemClassification.filler, "Character"),
    ItemName.policemarksman_unlocked: LB1ItemData(base_item_id + 14, ItemClassification.filler, "Character"),
    ItemName.clayface_unlocked: LB1ItemData(base_item_id + 15, ItemClassification.progression, "Character"),
    ItemName.mrfreeze_unlocked: LB1ItemData(base_item_id + 16, ItemClassification.progression, "Character"),
    ItemName.poisonivy_unlocked: LB1ItemData(base_item_id + 17, ItemClassification.progression, "Character"),
    ItemName.twoface_unlocked: LB1ItemData(base_item_id + 18, ItemClassification.progression, "Character"),
    ItemName.riddler_unlocked: LB1ItemData(base_item_id + 19, ItemClassification.progression, "Character"),
    ItemName.bane_unlocked: LB1ItemData(base_item_id + 20, ItemClassification.progression, "Character"),
    ItemName.catwoman_unlocked: LB1ItemData(base_item_id + 21, ItemClassification.progression, "Character"),
    ItemName.catwomanclassic_unlocked: LB1ItemData(base_item_id + 22, ItemClassification.progression, "Character"),
    ItemName.killercroc_unlocked: LB1ItemData(base_item_id + 23, ItemClassification.progression, "Character"),
    ItemName.manbat_unlocked: LB1ItemData(base_item_id + 24, ItemClassification.progression, "Character"),
    ItemName.penguin_unlocked: LB1ItemData(base_item_id + 25, ItemClassification.progression, "Character"),
    ItemName.harleyquinn_unlocked: LB1ItemData(base_item_id + 26, ItemClassification.progression, "Character"),
    ItemName.scarecrow_unlocked: LB1ItemData(base_item_id + 27, ItemClassification.progression, "Character"),
    ItemName.killermoth_unlocked: LB1ItemData(base_item_id + 28, ItemClassification.progression, "Character"),
    ItemName.madhatter_unlocked: LB1ItemData(base_item_id + 29, ItemClassification.progression, "Character"),
    ItemName.joker_unlocked: LB1ItemData(base_item_id + 30, ItemClassification.progression, "Character"),
    ItemName.jokertropical_unlocked: LB1ItemData(base_item_id + 31, ItemClassification.progression, "Character"),
    ItemName.poisonivygoon_unlocked: LB1ItemData(base_item_id + 32, ItemClassification.filler, "Character"),
    ItemName.zoosweeper_unlocked: LB1ItemData(base_item_id + 33, ItemClassification.filler, "Character"),
    ItemName.freezegirl_unlocked: LB1ItemData(base_item_id + 34, ItemClassification.filler, "Character"),
    ItemName.yeti_unlocked: LB1ItemData(base_item_id + 35, ItemClassification.filler, "Character"),
    ItemName.riddlergoon_unlocked: LB1ItemData(base_item_id + 36, ItemClassification.filler, "Character"),
    ItemName.riddlerhenchman_unlocked: LB1ItemData(base_item_id + 37, ItemClassification.filler, "Character"),
    ItemName.penguingoon_unlocked: LB1ItemData(base_item_id + 38, ItemClassification.filler, "Character"),
    ItemName.penguinhenchman_unlocked: LB1ItemData(base_item_id + 39, ItemClassification.filler, "Character"),
    ItemName.penguinminion_unlocked: LB1ItemData(base_item_id + 40, ItemClassification.useful, "Character"),
    ItemName.jokergoon_unlocked: LB1ItemData(base_item_id + 41, ItemClassification.progression, "Character"),
    ItemName.jokerhenchman_unlocked: LB1ItemData(base_item_id + 42, ItemClassification.filler, "Character"),
    ItemName.clowngoon_unlocked: LB1ItemData(base_item_id + 43, ItemClassification.filler, "Character"),
    ItemName.hush_unlocked: LB1ItemData(base_item_id + 44, ItemClassification.useful, "Hard Character"),
    ItemName.rasalghul_unlocked: LB1ItemData(base_item_id + 45, ItemClassification.useful, "Hard Character"),
    # ItemName.hero1_unlocked: LB1ItemData(base_item_id + 46, ItemClassification.progression, "Character"),
    # ItemName.hero2_unlocked: LB1ItemData(base_item_id + 47, ItemClassification.progression, "Character"),
    ItemName.batmobile_unlocked: LB1ItemData(base_item_id + 48, ItemClassification.progression, "Character"),
    ItemName.batcycle_unlocked: LB1ItemData(base_item_id + 49, ItemClassification.progression, "Character"),
    ItemName.policecar_unlocked: LB1ItemData(base_item_id + 50,
                                             ItemClassification.progression_deprioritized, "Character"),
    ItemName.policebike_unlocked: LB1ItemData(base_item_id + 51, ItemClassification.progression_deprioritized,
                                              "Character"),
    ItemName.policevan_unlocked: LB1ItemData(base_item_id + 52,
                                             ItemClassification.progression_deprioritized, "Character"),
    ItemName.battank_unlocked: LB1ItemData(base_item_id + 53,
                                           ItemClassification.progression_deprioritized, "Character"),
    ItemName.catmotorcycle_unlocked: LB1ItemData(base_item_id + 54,
                                                 ItemClassification.progression_deprioritized, "Character"),
    ItemName.armouredtruck_unlocked: LB1ItemData(base_item_id + 55, ItemClassification.progression_deprioritized,
                                                 "Character"),
    ItemName.freezekart_unlocked: LB1ItemData(base_item_id + 56,
                                              ItemClassification.progression_deprioritized, "Character"),
    ItemName.hammertruck_unlocked: LB1ItemData(base_item_id + 57,
                                               ItemClassification.progression_deprioritized, "Character"),
    ItemName.jokervan_unlocked: LB1ItemData(base_item_id + 58,
                                            ItemClassification.progression_deprioritized, "Character"),
    ItemName.garbagetruck_unlocked: LB1ItemData(base_item_id + 59,
                                                ItemClassification.progression_deprioritized, "Character"),
    ItemName.batboat_unlocked: LB1ItemData(base_item_id + 60, ItemClassification.progression, "Character"),
    ItemName.robinswatercraft_unlocked: LB1ItemData(base_item_id + 61, ItemClassification.progression, "Character"),
    ItemName.robinssubmarine_unlocked: LB1ItemData(base_item_id + 62,
                                                   ItemClassification.progression_deprioritized, "Character"),
    ItemName.policewatercraft_unlocked: LB1ItemData(base_item_id + 63,
                                                    ItemClassification.progression_deprioritized, "Character"),
    ItemName.policeboat_unlocked: LB1ItemData(base_item_id + 64, ItemClassification.progression_deprioritized,
                                              "Character"),
    ItemName.penguinsubmarine_unlocked: LB1ItemData(base_item_id + 65, ItemClassification.progression, "Character"),
    ItemName.swamprider_unlocked: LB1ItemData(base_item_id + 66, ItemClassification.progression, "Character"),
    ItemName.penguingoonsub_unlocked: LB1ItemData(base_item_id + 67,
                                                  ItemClassification.progression_deprioritized, "Character"),
    ItemName.iceberg_unlocked: LB1ItemData(base_item_id + 68,
                                           ItemClassification.progression_deprioritized, "Character"),
    ItemName.steamboat_unlocked: LB1ItemData(base_item_id + 69, ItemClassification.progression_deprioritized,
                                             "Character"),
    ItemName.batwing_unlocked: LB1ItemData(base_item_id + 70, ItemClassification.progression, "Character"),
    ItemName.batcopter_unlocked: LB1ItemData(base_item_id + 71, ItemClassification.progression, "Character"),
    ItemName.harbourhelicopter_unlocked: LB1ItemData(base_item_id + 72,
                                                     ItemClassification.progression_deprioritized, "Character"),
    ItemName.policehelicopter_unlocked: LB1ItemData(base_item_id + 73,
                                                    ItemClassification.progression_deprioritized, "Character"),
    ItemName.privatejet_unlocked: LB1ItemData(base_item_id + 74, ItemClassification.progression_deprioritized,
                                              "Character"),
    ItemName.jokerhelicopter_unlocked: LB1ItemData(base_item_id + 75, ItemClassification.progression, "Character"),
    ItemName.biplane_unlocked: LB1ItemData(base_item_id + 76, ItemClassification.progression, "Character"),
    ItemName.goonhelicopter_unlocked: LB1ItemData(base_item_id + 77,
                                                  ItemClassification.progression_deprioritized, "Character"),
    ItemName.riddlerjet_unlocked: LB1ItemData(base_item_id + 78,
                                              ItemClassification.progression_deprioritized, "Character"),
    ItemName.glider_unlocked: LB1ItemData(base_item_id + 79, ItemClassification.progression_deprioritized,
                                          "Character"),
}

suit_item_table: Dict[str, LB1ItemData] = {
    # "Batsuit": LB1ItemData(base_item_id + 80, ItemClassification.progression),
    ItemName.heatprotectsuit: LB1ItemData(base_item_id + 81, ItemClassification.progression, "Suit"),
    ItemName.glidesuit: LB1ItemData(base_item_id + 82, ItemClassification.progression, "Suit"),
    ItemName.demosuit: LB1ItemData(base_item_id + 83, ItemClassification.progression, "Suit"),
    ItemName.sonicsuit: LB1ItemData(base_item_id + 84, ItemClassification.progression, "Suit"),
    # "Robinsuit": LB1ItemData(base_item_id + 85, ItemClassification.progression),
    ItemName.watersuit: LB1ItemData(base_item_id + 86, ItemClassification.progression, "Suit"),
    ItemName.techsuit: LB1ItemData(base_item_id + 87, ItemClassification.progression, "Suit"),
    ItemName.magsuit: LB1ItemData(base_item_id + 88, ItemClassification.progression, "Suit"),
    ItemName.attractsuit: LB1ItemData(base_item_id + 89, ItemClassification.progression, "Suit"),
}

filler_item_table: Dict[str, LB1ItemData] = {
    ItemName.purp: LB1ItemData(base_item_id + 90, ItemClassification.filler, "Filler"),
}

minikit_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_min: LB1ItemData(base_item_id + 100, count=10),
    ItemName.air_min: LB1ItemData(base_item_id + 101, count=10),
    ItemName.tfc_min: LB1ItemData(base_item_id + 102, count=10),
    ItemName.apa_min: LB1ItemData(base_item_id + 103, count=10),
    ItemName.tfo_min: LB1ItemData(base_item_id + 104, count=10),
    ItemName.tsga_min: LB1ItemData(base_item_id + 105, count=10),
    ItemName.bbb_min: LB1ItemData(base_item_id + 106, count=10),
    ItemName.utc_min: LB1ItemData(base_item_id + 107, count=10),
    ItemName.zc_min: LB1ItemData(base_item_id + 108, count=10),
    ItemName.pl_min: LB1ItemData(base_item_id + 109, count=10),
    ItemName.jht_min: LB1ItemData(base_item_id + 110, count=10),
    ItemName.lfabt_min: LB1ItemData(base_item_id + 111, count=10),
    ItemName.fotb_min: LB1ItemData(base_item_id + 112, count=10),
    ItemName.itdn_min: LB1ItemData(base_item_id + 113, count=10),
    ItemName.tttot_min: LB1ItemData(base_item_id + 114, count=10),
    ItemName.trmaw_min: LB1ItemData(base_item_id + 115, count=10),
    ItemName.otr_min: LB1ItemData(base_item_id + 116, count=10),
    ItemName.gf_min: LB1ItemData(base_item_id + 117, count=10),
    ItemName.aet_min: LB1ItemData(base_item_id + 118, count=10),
    ItemName.bb_min: LB1ItemData(base_item_id + 119, count=10),
    ItemName.rtd_min: LB1ItemData(base_item_id + 120, count=10),
    ItemName.sts_min: LB1ItemData(base_item_id + 121, count=10),
    ItemName.hag_min: LB1ItemData(base_item_id + 122, count=10),
    ItemName.adr_min: LB1ItemData(base_item_id + 123, count=10),
    ItemName.aw_min: LB1ItemData(base_item_id + 124, count=10),
    ItemName.asftc_min: LB1ItemData(base_item_id + 125, count=10),
    ItemName.bbpl_min: LB1ItemData(base_item_id + 126, count=10),
    ItemName.tjm_min: LB1ItemData(base_item_id + 127, count=10),
    ItemName.tlotn_min: LB1ItemData(base_item_id + 128, count=10),
    ItemName.dol_min: LB1ItemData(base_item_id + 129, count=10),
}


minikit2_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_min2: LB1ItemData(base_item_id + 130, count=5),
    ItemName.air_min2: LB1ItemData(base_item_id + 131, count=5),
    ItemName.tfc_min2: LB1ItemData(base_item_id + 132, count=5),
    ItemName.apa_min2: LB1ItemData(base_item_id + 133, count=5),
    ItemName.tfo_min2: LB1ItemData(base_item_id + 134, count=5),
    ItemName.tsga_min2: LB1ItemData(base_item_id + 135, count=5),
    ItemName.bbb_min2: LB1ItemData(base_item_id + 136, count=5),
    ItemName.utc_min2: LB1ItemData(base_item_id + 137, count=5),
    ItemName.zc_min2: LB1ItemData(base_item_id + 138, count=5),
    ItemName.pl_min2: LB1ItemData(base_item_id + 139, count=5),
    ItemName.jht_min2: LB1ItemData(base_item_id + 140, count=5),
    ItemName.lfabt_min2: LB1ItemData(base_item_id + 141, count=5),
    ItemName.fotb_min2: LB1ItemData(base_item_id + 142, count=5),
    ItemName.itdn_min2: LB1ItemData(base_item_id + 143, count=5),
    ItemName.tttot_min2: LB1ItemData(base_item_id + 144, count=5),
    ItemName.trmaw_min2: LB1ItemData(base_item_id + 145, count=5),
    ItemName.otr_min2: LB1ItemData(base_item_id + 146, count=5),
    ItemName.gf_min2: LB1ItemData(base_item_id + 147, count=5),
    ItemName.aet_min2: LB1ItemData(base_item_id + 148, count=5),
    ItemName.bb_min2: LB1ItemData(base_item_id + 149, count=5),
    ItemName.rtd_min2: LB1ItemData(base_item_id + 150, count=5),
    ItemName.sts_min2: LB1ItemData(base_item_id + 151, count=5),
    ItemName.hag_min2: LB1ItemData(base_item_id + 152, count=5),
    ItemName.adr_min2: LB1ItemData(base_item_id + 153, count=5),
    ItemName.aw_min2: LB1ItemData(base_item_id + 154, count=5),
    ItemName.asftc_min2: LB1ItemData(base_item_id + 155, count=5),
    ItemName.bbpl_min2: LB1ItemData(base_item_id + 156, count=5),
    ItemName.tjm_min2: LB1ItemData(base_item_id + 157, count=5),
    ItemName.tlotn_min2: LB1ItemData(base_item_id + 158, count=5),
    ItemName.dol_min2: LB1ItemData(base_item_id + 159, count=5),
}


minikit5_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_min5: LB1ItemData(base_item_id + 160, count=2),
    ItemName.air_min5: LB1ItemData(base_item_id + 161, count=2),
    ItemName.tfc_min5: LB1ItemData(base_item_id + 162, count=2),
    ItemName.apa_min5: LB1ItemData(base_item_id + 163, count=2),
    ItemName.tfo_min5: LB1ItemData(base_item_id + 164, count=2),
    ItemName.tsga_min5: LB1ItemData(base_item_id + 165, count=2),
    ItemName.bbb_min5: LB1ItemData(base_item_id + 166, count=2),
    ItemName.utc_min5: LB1ItemData(base_item_id + 167, count=2),
    ItemName.zc_min5: LB1ItemData(base_item_id + 168, count=2),
    ItemName.pl_min5: LB1ItemData(base_item_id + 169, count=2),
    ItemName.jht_min5: LB1ItemData(base_item_id + 170, count=2),
    ItemName.lfabt_min5: LB1ItemData(base_item_id + 171, count=2),
    ItemName.fotb_min5: LB1ItemData(base_item_id + 172, count=2),
    ItemName.itdn_min5: LB1ItemData(base_item_id + 173, count=2),
    ItemName.tttot_min5: LB1ItemData(base_item_id + 174, count=2),
    ItemName.trmaw_min5: LB1ItemData(base_item_id + 175, count=2),
    ItemName.otr_min5: LB1ItemData(base_item_id + 176, count=2),
    ItemName.gf_min5: LB1ItemData(base_item_id + 177, count=2),
    ItemName.aet_min5: LB1ItemData(base_item_id + 178, count=2),
    ItemName.bb_min5: LB1ItemData(base_item_id + 179, count=2),
    ItemName.rtd_min5: LB1ItemData(base_item_id + 180, count=2),
    ItemName.sts_min5: LB1ItemData(base_item_id + 181, count=2),
    ItemName.hag_min5: LB1ItemData(base_item_id + 182, count=2),
    ItemName.adr_min5: LB1ItemData(base_item_id + 183, count=2),
    ItemName.aw_min5: LB1ItemData(base_item_id + 184, count=2),
    ItemName.asftc_min5: LB1ItemData(base_item_id + 185, count=2),
    ItemName.bbpl_min5: LB1ItemData(base_item_id + 186, count=2),
    ItemName.tjm_min5: LB1ItemData(base_item_id + 187, count=2),
    ItemName.tlotn_min5: LB1ItemData(base_item_id + 188, count=2),
    ItemName.dol_min5: LB1ItemData(base_item_id + 189, count=2),
}


minikit10_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_min10: LB1ItemData(base_item_id + 190),
    ItemName.air_min10: LB1ItemData(base_item_id + 191),
    ItemName.tfc_min10: LB1ItemData(base_item_id + 192),
    ItemName.apa_min10: LB1ItemData(base_item_id + 193),
    ItemName.tfo_min10: LB1ItemData(base_item_id + 194),
    ItemName.tsga_min10: LB1ItemData(base_item_id + 195),
    ItemName.bbb_min10: LB1ItemData(base_item_id + 196),
    ItemName.utc_min10: LB1ItemData(base_item_id + 197),
    ItemName.zc_min10: LB1ItemData(base_item_id + 198),
    ItemName.pl_min10: LB1ItemData(base_item_id + 199),
    ItemName.jht_min10: LB1ItemData(base_item_id + 200),
    ItemName.lfabt_min10: LB1ItemData(base_item_id + 201),
    ItemName.fotb_min10: LB1ItemData(base_item_id + 202),
    ItemName.itdn_min10: LB1ItemData(base_item_id + 203),
    ItemName.tttot_min10: LB1ItemData(base_item_id + 204),
    ItemName.trmaw_min10: LB1ItemData(base_item_id + 205),
    ItemName.otr_min10: LB1ItemData(base_item_id + 206),
    ItemName.gf_min10: LB1ItemData(base_item_id + 207),
    ItemName.aet_min10: LB1ItemData(base_item_id + 208),
    ItemName.bb_min10: LB1ItemData(base_item_id + 209),
    ItemName.rtd_min10: LB1ItemData(base_item_id + 210),
    ItemName.sts_min10: LB1ItemData(base_item_id + 211),
    ItemName.hag_min10: LB1ItemData(base_item_id + 212),
    ItemName.adr_min10: LB1ItemData(base_item_id + 213),
    ItemName.aw_min10: LB1ItemData(base_item_id + 214),
    ItemName.asftc_min10: LB1ItemData(base_item_id + 215),
    ItemName.bbpl_min10: LB1ItemData(base_item_id + 216),
    ItemName.tjm_min10: LB1ItemData(base_item_id + 217),
    ItemName.tlotn_min10: LB1ItemData(base_item_id + 218),
    ItemName.dol_min10: LB1ItemData(base_item_id + 219),
}


hostage_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_host: LB1ItemData(base_item_id + 400, type="Hostage"),
    ItemName.air_host: LB1ItemData(base_item_id + 401, type="Hostage"),
    ItemName.apa_host: LB1ItemData(base_item_id + 402, type="Hostage"),
    ItemName.tfo_host: LB1ItemData(base_item_id + 403, type="Hostage"),
    ItemName.tsga_host: LB1ItemData(base_item_id + 404, type="Hostage"),
    ItemName.utc_host: LB1ItemData(base_item_id + 405, type="Hostage"),
    ItemName.zc_host: LB1ItemData(base_item_id + 406, type="Hostage"),
    ItemName.pl_host: LB1ItemData(base_item_id + 407, type="Hostage"),
    ItemName.jht_host: LB1ItemData(base_item_id + 408, type="Hostage"),
    ItemName.lfabt_host: LB1ItemData(base_item_id + 409, type="Hostage"),
    ItemName.itdn_host: LB1ItemData(base_item_id + 410, type="Hostage"),
    ItemName.tttot_host: LB1ItemData(base_item_id + 411, type="Hostage"),
    ItemName.trmaw_host: LB1ItemData(base_item_id + 412, type="Hostage"),
    ItemName.otr_host: LB1ItemData(base_item_id + 413, type="Hostage"),
    ItemName.gf_host: LB1ItemData(base_item_id + 414, type="Hostage"),
    ItemName.aet_host: LB1ItemData(base_item_id + 415, type="Hostage"),
    ItemName.bb_host: LB1ItemData(base_item_id + 416, type="Hostage"),
    ItemName.rtd_host: LB1ItemData(base_item_id + 417, type="Hostage"),
    ItemName.sts_host: LB1ItemData(base_item_id + 418, type="Hostage"),
    ItemName.adr_host: LB1ItemData(base_item_id + 419, type="Hostage"),
    ItemName.aw_host: LB1ItemData(base_item_id + 420, type="Hostage"),
    ItemName.asftc_host: LB1ItemData(base_item_id + 421, type="Hostage"),
    ItemName.tjm_host: LB1ItemData(base_item_id + 422, type="Hostage"),
    ItemName.tlotn_host: LB1ItemData(base_item_id + 423, type="Hostage"),
    ItemName.dol_host: LB1ItemData(base_item_id + 424, type="Hostage"),
}

level_unlocked_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_lvl: LB1ItemData(base_item_id + 425, ItemClassification.progression, "Level"),
    ItemName.air_lvl: LB1ItemData(base_item_id + 426, ItemClassification.progression, "Level"),
    ItemName.tfc_lvl: LB1ItemData(base_item_id + 427, ItemClassification.progression, "Level"),
    ItemName.apa_lvl: LB1ItemData(base_item_id + 428, ItemClassification.progression, "Level"),
    ItemName.tfo_lvl: LB1ItemData(base_item_id + 429, ItemClassification.progression, "Level"),
    ItemName.tsga_lvl: LB1ItemData(base_item_id + 430, ItemClassification.progression, "Level"),
    ItemName.bbb_lvl: LB1ItemData(base_item_id + 431, ItemClassification.progression, "Level"),
    ItemName.utc_lvl: LB1ItemData(base_item_id + 432, ItemClassification.progression, "Level"),
    ItemName.zc_lvl: LB1ItemData(base_item_id + 433, ItemClassification.progression, "Level"),
    ItemName.pl_lvl: LB1ItemData(base_item_id + 434, ItemClassification.progression, "Level"),
    ItemName.jht_lvl: LB1ItemData(base_item_id + 435, ItemClassification.progression, "Level"),
    ItemName.lfabt_lvl: LB1ItemData(base_item_id + 436, ItemClassification.progression, "Level"),
    ItemName.fotb_lvl: LB1ItemData(base_item_id + 437, ItemClassification.progression, "Level"),
    ItemName.itdn_lvl: LB1ItemData(base_item_id + 438, ItemClassification.progression, "Level"),
    ItemName.tttot_lvl: LB1ItemData(base_item_id + 439, ItemClassification.progression, "Level"),
    ItemName.trmaw_lvl: LB1ItemData(base_item_id + 440, ItemClassification.progression, "Level"),
    ItemName.otr_lvl: LB1ItemData(base_item_id + 441, ItemClassification.progression, "Level"),
    ItemName.gf_lvl: LB1ItemData(base_item_id + 442, ItemClassification.progression, "Level"),
    ItemName.aet_lvl: LB1ItemData(base_item_id + 443, ItemClassification.progression, "Level"),
    ItemName.bb_lvl: LB1ItemData(base_item_id + 444, ItemClassification.progression, "Level"),
    ItemName.rtd_lvl: LB1ItemData(base_item_id + 445, ItemClassification.progression, "Level"),
    ItemName.sts_lvl: LB1ItemData(base_item_id + 446, ItemClassification.progression, "Level"),
    ItemName.hag_lvl: LB1ItemData(base_item_id + 447, ItemClassification.progression, "Level"),
    ItemName.adr_lvl: LB1ItemData(base_item_id + 448, ItemClassification.progression, "Level"),
    ItemName.aw_lvl: LB1ItemData(base_item_id + 449, ItemClassification.progression, "Level"),
    ItemName.asftc_lvl: LB1ItemData(base_item_id + 450, ItemClassification.progression, "Level"),
    ItemName.bbpl_lvl: LB1ItemData(base_item_id + 451, ItemClassification.progression, "Level"),
    ItemName.tjm_lvl: LB1ItemData(base_item_id + 452, ItemClassification.progression, "Level"),
    ItemName.tlotn_lvl: LB1ItemData(base_item_id + 453, ItemClassification.progression, "Level"),
    ItemName.dol_lvl: LB1ItemData(base_item_id + 454, ItemClassification.progression, "Level"),
}

true_status_item_table: Dict[str, LB1ItemData] = {
    ItemName.ycbob_ts: LB1ItemData(base_item_id + 455, type="True Status"),
    ItemName.air_ts: LB1ItemData(base_item_id + 456, type="True Status"),
    ItemName.tfc_ts: LB1ItemData(base_item_id + 457, type="True Status"),
    ItemName.apa_ts: LB1ItemData(base_item_id + 458, type="True Status"),
    ItemName.tfo_ts: LB1ItemData(base_item_id + 459, type="True Status"),
    ItemName.tsga_ts: LB1ItemData(base_item_id + 460, type="True Status"),
    ItemName.bbb_ts: LB1ItemData(base_item_id + 461, type="True Status"),
    ItemName.utc_ts: LB1ItemData(base_item_id + 462, type="True Status"),
    ItemName.zc_ts: LB1ItemData(base_item_id + 463, type="True Status"),
    ItemName.pl_ts: LB1ItemData(base_item_id + 464, type="True Status"),
    ItemName.jht_ts: LB1ItemData(base_item_id + 465, type="True Status"),
    ItemName.lfabt_ts: LB1ItemData(base_item_id + 466, type="True Status"),
    ItemName.fotb_ts: LB1ItemData(base_item_id + 467, type="True Status"),
    ItemName.itdn_ts: LB1ItemData(base_item_id + 468, type="True Status"),
    ItemName.tttot_ts: LB1ItemData(base_item_id + 469, type="True Status"),
    ItemName.trmaw_ts: LB1ItemData(base_item_id + 470, type="True Status"),
    ItemName.otr_ts: LB1ItemData(base_item_id + 471, type="True Status"),
    ItemName.gf_ts: LB1ItemData(base_item_id + 472, type="True Status"),
    ItemName.aet_ts: LB1ItemData(base_item_id + 473, type="True Status"),
    ItemName.bb_ts: LB1ItemData(base_item_id + 474, type="True Status"),
    ItemName.rtd_ts: LB1ItemData(base_item_id + 475, type="True Status"),
    ItemName.sts_ts: LB1ItemData(base_item_id + 476, type="True Status"),
    ItemName.hag_ts: LB1ItemData(base_item_id + 477, type="True Status"),
    ItemName.adr_ts: LB1ItemData(base_item_id + 478, type="True Status"),
    ItemName.aw_ts: LB1ItemData(base_item_id + 479, type="True Status"),
    ItemName.asftc_ts: LB1ItemData(base_item_id + 480, type="True Status"),
    ItemName.bbpl_ts: LB1ItemData(base_item_id + 481, type="True Status"),
    ItemName.tjm_ts: LB1ItemData(base_item_id + 482, type="True Status"),
    ItemName.tlotn_ts: LB1ItemData(base_item_id + 483, type="True Status"),
    ItemName.dol_ts: LB1ItemData(base_item_id + 484, type="True Status"),
}

red_brick_unlocked_table: Dict[str, LB1ItemData] = {
    # 485 is adaptive difficulty
    ItemName.silhouettes: LB1ItemData(base_item_id + 486, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.beepbeep: LB1ItemData(base_item_id + 487, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.icerink: LB1ItemData(base_item_id + 488, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.disguise: LB1ItemData(base_item_id + 489, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.extratoggle: LB1ItemData(base_item_id + 490, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.scorex2: LB1ItemData(base_item_id + 491, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.scorex4: LB1ItemData(base_item_id + 492, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.scorex6: LB1ItemData(base_item_id + 493, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.scorex8: LB1ItemData(base_item_id + 494, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.scorex10: LB1ItemData(base_item_id + 495, ItemClassification.progression, "Red Brick Unlocked"),
    ItemName.studmagnet: LB1ItemData(base_item_id + 496, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.charstuds: LB1ItemData(base_item_id + 497, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.minidetect: LB1ItemData(base_item_id + 498, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.powerdetect: LB1ItemData(base_item_id + 499, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.alwaysscore: LB1ItemData(base_item_id + 500, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fastbuild: LB1ItemData(base_item_id + 501, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.immunefreeze: LB1ItemData(base_item_id + 502, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.regenhearts: LB1ItemData(base_item_id + 503, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.extrahearts: LB1ItemData(base_item_id + 504, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.invincibility: LB1ItemData(base_item_id + 505, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fastgrap: LB1ItemData(base_item_id + 506, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fastbat: LB1ItemData(base_item_id + 507, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.moretargets: LB1ItemData(base_item_id + 508, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.flamingbat: LB1ItemData(base_item_id + 509, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.slam: LB1ItemData(base_item_id + 510, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.moredet: LB1ItemData(base_item_id + 511, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.armourplating: LB1ItemData(base_item_id + 512, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.sonicpain: LB1ItemData(base_item_id + 513, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.areaeffect: LB1ItemData(base_item_id + 514, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.bats: LB1ItemData(base_item_id + 515, ItemClassification.filler, "Red Brick Unlocked"),
    ItemName.freezebatarang: LB1ItemData(base_item_id + 516, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.decoy: LB1ItemData(base_item_id + 517, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fastwalk: LB1ItemData(base_item_id + 518, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.fasterpieces: LB1ItemData(base_item_id + 519, ItemClassification.useful, "Red Brick Unlocked"),
    ItemName.piecedetect: LB1ItemData(base_item_id + 520, ItemClassification.useful, "Red Brick Unlocked"),
}


all_item_table = {
    **character_item_table,
    # **hard_character_item_table,
    **suit_item_table,
    **minikit_item_table,
    **minikit2_item_table,
    **minikit5_item_table,
    **minikit10_item_table,
    **hostage_item_table,
    **level_unlocked_item_table,
    **true_status_item_table,
    **red_brick_unlocked_table,
    **filler_item_table,
}

minikit_table = {
    **minikit_item_table,
    **minikit2_item_table,
    **minikit5_item_table,
    **minikit10_item_table,
}

hostage_names_set = set(hostage_item_table.keys())
