from BaseClasses import Item, ItemClassification
from typing import NamedTuple, Optional, Dict

base_item_id: int = 400000

class LB1Item(Item):
    game: str = "Lego Batman: The Video Game"

class LB1ItemData(NamedTuple):
    code: Optional[int] = None
    classification: ItemClassification = ItemClassification.progression_deprioritized_skip_balancing

#TODO: add in progression classification based off of win con (look at manual's implementation - need to decide win cons first)
minikit_item_table: Dict[str, LB1ItemData] = {
    "You can Bank on Batman: Minikit 1": LB1ItemData(base_item_id + 100),
    "You can Bank on Batman: Minikit 2": LB1ItemData(base_item_id + 101),
    "You can Bank on Batman: Minikit 3": LB1ItemData(base_item_id + 102),
    "You can Bank on Batman: Minikit 4": LB1ItemData(base_item_id + 103),
    "You can Bank on Batman: Minikit 5": LB1ItemData(base_item_id + 104),
    "You can Bank on Batman: Minikit 6": LB1ItemData(base_item_id + 105),
    "You can Bank on Batman: Minikit 7": LB1ItemData(base_item_id + 106),
    "You can Bank on Batman: Minikit 8": LB1ItemData(base_item_id + 107),
    "You can Bank on Batman: Minikit 9": LB1ItemData(base_item_id + 108),
    "You can Bank on Batman: Minikit 10": LB1ItemData(base_item_id + 109),
    
    "An Icy Reception: Minikit 1": LB1ItemData(base_item_id + 110),
    "An Icy Reception: Minikit 2": LB1ItemData(base_item_id + 111),
    "An Icy Reception: Minikit 3": LB1ItemData(base_item_id + 112),
    "An Icy Reception: Minikit 4": LB1ItemData(base_item_id + 113),
    "An Icy Reception: Minikit 5": LB1ItemData(base_item_id + 114),
    "An Icy Reception: Minikit 6": LB1ItemData(base_item_id + 115),
    "An Icy Reception: Minikit 7": LB1ItemData(base_item_id + 116),
    "An Icy Reception: Minikit 8": LB1ItemData(base_item_id + 117),
    "An Icy Reception: Minikit 9": LB1ItemData(base_item_id + 118),
    "An Icy Reception: Minikit 10": LB1ItemData(base_item_id + 119),

    "Two-Face Chase: Minikit 1": LB1ItemData(base_item_id + 120),
    "Two-Face Chase: Minikit 2": LB1ItemData(base_item_id + 121),
    "Two-Face Chase: Minikit 3": LB1ItemData(base_item_id + 122),
    "Two-Face Chase: Minikit 4": LB1ItemData(base_item_id + 123),
    "Two-Face Chase: Minikit 5": LB1ItemData(base_item_id + 124),
    "Two-Face Chase: Minikit 6": LB1ItemData(base_item_id + 125),
    "Two-Face Chase: Minikit 7": LB1ItemData(base_item_id + 126),
    "Two-Face Chase: Minikit 8": LB1ItemData(base_item_id + 127),
    "Two-Face Chase: Minikit 9": LB1ItemData(base_item_id + 128),
    "Two-Face Chase: Minikit 10": LB1ItemData(base_item_id + 129),

    "A Poisonous Appointment: Minikit 1": LB1ItemData(base_item_id + 130),
    "A Poisonous Appointment: Minikit 2": LB1ItemData(base_item_id + 131),
    "A Poisonous Appointment: Minikit 3": LB1ItemData(base_item_id + 132),
    "A Poisonous Appointment: Minikit 4": LB1ItemData(base_item_id + 133),
    "A Poisonous Appointment: Minikit 5": LB1ItemData(base_item_id + 134),
    "A Poisonous Appointment: Minikit 6": LB1ItemData(base_item_id + 135),
    "A Poisonous Appointment: Minikit 7": LB1ItemData(base_item_id + 136),
    "A Poisonous Appointment: Minikit 8": LB1ItemData(base_item_id + 137),
    "A Poisonous Appointment: Minikit 9": LB1ItemData(base_item_id + 138),
    "A Poisonous Appointment: Minikit 10": LB1ItemData(base_item_id + 139),

    "The Face-Off: Minikit 1": LB1ItemData(base_item_id + 140),
    "The Face-Off: Minikit 2": LB1ItemData(base_item_id + 141),
    "The Face-Off: Minikit 3": LB1ItemData(base_item_id + 142),
    "The Face-Off: Minikit 4": LB1ItemData(base_item_id + 143),
    "The Face-Off: Minikit 5": LB1ItemData(base_item_id + 144),
    "The Face-Off: Minikit 6": LB1ItemData(base_item_id + 145),
    "The Face-Off: Minikit 7": LB1ItemData(base_item_id + 146),
    "The Face-Off: Minikit 8": LB1ItemData(base_item_id + 147),
    "The Face-Off: Minikit 9": LB1ItemData(base_item_id + 148),
    "The Face-Off: Minikit 10": LB1ItemData(base_item_id + 149),

    "There She Goes Again: Minikit 1": LB1ItemData(base_item_id + 150),
    "There She Goes Again: Minikit 2": LB1ItemData(base_item_id + 151),
    "There She Goes Again: Minikit 3": LB1ItemData(base_item_id + 152),
    "There She Goes Again: Minikit 4": LB1ItemData(base_item_id + 153),
    "There She Goes Again: Minikit 5": LB1ItemData(base_item_id + 154),
    "There She Goes Again: Minikit 6": LB1ItemData(base_item_id + 155),
    "There She Goes Again: Minikit 7": LB1ItemData(base_item_id + 156),
    "There She Goes Again: Minikit 8": LB1ItemData(base_item_id + 157),
    "There She Goes Again: Minikit 9": LB1ItemData(base_item_id + 158),
    "There She Goes Again: Minikit 10": LB1ItemData(base_item_id + 159),

    "Batboat Battle: Minikit 1": LB1ItemData(base_item_id + 160),
    "Batboat Battle: Minikit 2": LB1ItemData(base_item_id + 161),
    "Batboat Battle: Minikit 3": LB1ItemData(base_item_id + 162),
    "Batboat Battle: Minikit 4": LB1ItemData(base_item_id + 163),
    "Batboat Battle: Minikit 5": LB1ItemData(base_item_id + 164),
    "Batboat Battle: Minikit 6": LB1ItemData(base_item_id + 165),
    "Batboat Battle: Minikit 7": LB1ItemData(base_item_id + 166),
    "Batboat Battle: Minikit 8": LB1ItemData(base_item_id + 167),
    "Batboat Battle: Minikit 9": LB1ItemData(base_item_id + 168),
    "Batboat Battle: Minikit 10": LB1ItemData(base_item_id + 169),

    "Under the City: Minikit 1": LB1ItemData(base_item_id + 170),
    "Under the City: Minikit 2": LB1ItemData(base_item_id + 171),
    "Under the City: Minikit 3": LB1ItemData(base_item_id + 172),
    "Under the City: Minikit 4": LB1ItemData(base_item_id + 173),
    "Under the City: Minikit 5": LB1ItemData(base_item_id + 174),
    "Under the City: Minikit 6": LB1ItemData(base_item_id + 175),
    "Under the City: Minikit 7": LB1ItemData(base_item_id + 176),
    "Under the City: Minikit 8": LB1ItemData(base_item_id + 177),
    "Under the City: Minikit 9": LB1ItemData(base_item_id + 178),
    "Under the City: Minikit 10": LB1ItemData(base_item_id + 179),

    "Zoo's Company: Minikit 1": LB1ItemData(base_item_id + 180),
    "Zoo's Company: Minikit 2": LB1ItemData(base_item_id + 181),
    "Zoo's Company: Minikit 3": LB1ItemData(base_item_id + 182),
    "Zoo's Company: Minikit 4": LB1ItemData(base_item_id + 183),
    "Zoo's Company: Minikit 5": LB1ItemData(base_item_id + 184),
    "Zoo's Company: Minikit 6": LB1ItemData(base_item_id + 185),
    "Zoo's Company: Minikit 7": LB1ItemData(base_item_id + 186),
    "Zoo's Company: Minikit 8": LB1ItemData(base_item_id + 187),
    "Zoo's Company: Minikit 9": LB1ItemData(base_item_id + 188),
    "Zoo's Company: Minikit 10": LB1ItemData(base_item_id + 189),

    "Penguin's Lair: Minikit 1": LB1ItemData(base_item_id + 190),
    "Penguin's Lair: Minikit 2": LB1ItemData(base_item_id + 191),
    "Penguin's Lair: Minikit 3": LB1ItemData(base_item_id + 192),
    "Penguin's Lair: Minikit 4": LB1ItemData(base_item_id + 193),
    "Penguin's Lair: Minikit 5": LB1ItemData(base_item_id + 194),
    "Penguin's Lair: Minikit 6": LB1ItemData(base_item_id + 195),
    "Penguin's Lair: Minikit 7": LB1ItemData(base_item_id + 196),
    "Penguin's Lair: Minikit 8": LB1ItemData(base_item_id + 197),
    "Penguin's Lair: Minikit 9": LB1ItemData(base_item_id + 198),
    "Penguin's Lair: Minikit 10": LB1ItemData(base_item_id + 199),

    "Joker's Home Turf: Minikit 1": LB1ItemData(base_item_id + 200),
    "Joker's Home Turf: Minikit 2": LB1ItemData(base_item_id + 201),
    "Joker's Home Turf: Minikit 3": LB1ItemData(base_item_id + 202),
    "Joker's Home Turf: Minikit 4": LB1ItemData(base_item_id + 203),
    "Joker's Home Turf: Minikit 5": LB1ItemData(base_item_id + 204),
    "Joker's Home Turf: Minikit 6": LB1ItemData(base_item_id + 205),
    "Joker's Home Turf: Minikit 7": LB1ItemData(base_item_id + 206),
    "Joker's Home Turf: Minikit 8": LB1ItemData(base_item_id + 207),
    "Joker's Home Turf: Minikit 9": LB1ItemData(base_item_id + 208),
    "Joker's Home Turf: Minikit 10": LB1ItemData(base_item_id + 209),

    "Little Fun at the Big Top: Minikit 1": LB1ItemData(base_item_id + 210),
    "Little Fun at the Big Top: Minikit 2": LB1ItemData(base_item_id + 211),
    "Little Fun at the Big Top: Minikit 3": LB1ItemData(base_item_id + 212),
    "Little Fun at the Big Top: Minikit 4": LB1ItemData(base_item_id + 213),
    "Little Fun at the Big Top: Minikit 5": LB1ItemData(base_item_id + 214),
    "Little Fun at the Big Top: Minikit 6": LB1ItemData(base_item_id + 215),
    "Little Fun at the Big Top: Minikit 7": LB1ItemData(base_item_id + 216),
    "Little Fun at the Big Top: Minikit 8": LB1ItemData(base_item_id + 217),
    "Little Fun at the Big Top: Minikit 9": LB1ItemData(base_item_id + 218),
    "Little Fun at the Big Top: Minikit 10": LB1ItemData(base_item_id + 219),

    "Flight of the Bat: Minikit 1": LB1ItemData(base_item_id + 220),
    "Flight of the Bat: Minikit 2": LB1ItemData(base_item_id + 221),
    "Flight of the Bat: Minikit 3": LB1ItemData(base_item_id + 222),
    "Flight of the Bat: Minikit 4": LB1ItemData(base_item_id + 223),
    "Flight of the Bat: Minikit 5": LB1ItemData(base_item_id + 224),
    "Flight of the Bat: Minikit 6": LB1ItemData(base_item_id + 225),
    "Flight of the Bat: Minikit 7": LB1ItemData(base_item_id + 226),
    "Flight of the Bat: Minikit 8": LB1ItemData(base_item_id + 227),
    "Flight of the Bat: Minikit 9": LB1ItemData(base_item_id + 228),
    "Flight of the Bat: Minikit 10": LB1ItemData(base_item_id + 229),

    "In the Dark Night: Minikit 1": LB1ItemData(base_item_id + 230),
    "In the Dark Night: Minikit 2": LB1ItemData(base_item_id + 231),
    "In the Dark Night: Minikit 3": LB1ItemData(base_item_id + 232),
    "In the Dark Night: Minikit 4": LB1ItemData(base_item_id + 233),
    "In the Dark Night: Minikit 5": LB1ItemData(base_item_id + 234),
    "In the Dark Night: Minikit 6": LB1ItemData(base_item_id + 235),
    "In the Dark Night: Minikit 7": LB1ItemData(base_item_id + 236),
    "In the Dark Night: Minikit 8": LB1ItemData(base_item_id + 237),
    "In the Dark Night: Minikit 9": LB1ItemData(base_item_id + 238),
    "In the Dark Night: Minikit 10": LB1ItemData(base_item_id + 239),

    "To the Top of the Tower: Minikit 1": LB1ItemData(base_item_id + 240),
    "To the Top of the Tower: Minikit 2": LB1ItemData(base_item_id + 241),
    "To the Top of the Tower: Minikit 3": LB1ItemData(base_item_id + 242),
    "To the Top of the Tower: Minikit 4": LB1ItemData(base_item_id + 243),
    "To the Top of the Tower: Minikit 5": LB1ItemData(base_item_id + 244),
    "To the Top of the Tower: Minikit 6": LB1ItemData(base_item_id + 245),
    "To the Top of the Tower: Minikit 7": LB1ItemData(base_item_id + 246),
    "To the Top of the Tower: Minikit 8": LB1ItemData(base_item_id + 247),
    "To the Top of the Tower: Minikit 9": LB1ItemData(base_item_id + 248),
    "To the Top of the Tower: Minikit 10": LB1ItemData(base_item_id + 249),

    "The Riddler Makes a Withdrawal: Minikit 1": LB1ItemData(base_item_id + 250),
    "The Riddler Makes a Withdrawal: Minikit 2": LB1ItemData(base_item_id + 251),
    "The Riddler Makes a Withdrawal: Minikit 3": LB1ItemData(base_item_id + 252),
    "The Riddler Makes a Withdrawal: Minikit 4": LB1ItemData(base_item_id + 253),
    "The Riddler Makes a Withdrawal: Minikit 5": LB1ItemData(base_item_id + 254),
    "The Riddler Makes a Withdrawal: Minikit 6": LB1ItemData(base_item_id + 255),
    "The Riddler Makes a Withdrawal: Minikit 7": LB1ItemData(base_item_id + 256),
    "The Riddler Makes a Withdrawal: Minikit 8": LB1ItemData(base_item_id + 257),
    "The Riddler Makes a Withdrawal: Minikit 9": LB1ItemData(base_item_id + 258),
    "The Riddler Makes a Withdrawal: Minikit 10": LB1ItemData(base_item_id + 259),

    "On the Rocks: Minikit 1": LB1ItemData(base_item_id + 260),
    "On the Rocks: Minikit 2": LB1ItemData(base_item_id + 261),
    "On the Rocks: Minikit 3": LB1ItemData(base_item_id + 262),
    "On the Rocks: Minikit 4": LB1ItemData(base_item_id + 263),
    "On the Rocks: Minikit 5": LB1ItemData(base_item_id + 264),
    "On the Rocks: Minikit 6": LB1ItemData(base_item_id + 265),
    "On the Rocks: Minikit 7": LB1ItemData(base_item_id + 266),
    "On the Rocks: Minikit 8": LB1ItemData(base_item_id + 267),
    "On the Rocks: Minikit 9": LB1ItemData(base_item_id + 268),
    "On the Rocks: Minikit 10": LB1ItemData(base_item_id + 269),

    "Green Fingers: Minikit 1": LB1ItemData(base_item_id + 270),
    "Green Fingers: Minikit 2": LB1ItemData(base_item_id + 271),
    "Green Fingers: Minikit 3": LB1ItemData(base_item_id + 272),
    "Green Fingers: Minikit 4": LB1ItemData(base_item_id + 273),
    "Green Fingers: Minikit 5": LB1ItemData(base_item_id + 274),
    "Green Fingers: Minikit 6": LB1ItemData(base_item_id + 275),
    "Green Fingers: Minikit 7": LB1ItemData(base_item_id + 276),
    "Green Fingers: Minikit 8": LB1ItemData(base_item_id + 277),
    "Green Fingers: Minikit 9": LB1ItemData(base_item_id + 278),
    "Green Fingers: Minikit 10": LB1ItemData(base_item_id + 279),

    "An Enterprising Theft: Minikit 1": LB1ItemData(base_item_id + 280),
    "An Enterprising Theft: Minikit 2": LB1ItemData(base_item_id + 281),
    "An Enterprising Theft: Minikit 3": LB1ItemData(base_item_id + 282),
    "An Enterprising Theft: Minikit 4": LB1ItemData(base_item_id + 283),
    "An Enterprising Theft: Minikit 5": LB1ItemData(base_item_id + 284),
    "An Enterprising Theft: Minikit 6": LB1ItemData(base_item_id + 285),
    "An Enterprising Theft: Minikit 7": LB1ItemData(base_item_id + 286),
    "An Enterprising Theft: Minikit 8": LB1ItemData(base_item_id + 287),
    "An Enterprising Theft: Minikit 9": LB1ItemData(base_item_id + 288),
    "An Enterprising Theft: Minikit 10": LB1ItemData(base_item_id + 289),

    "Breaking Blocks: Minikit 1": LB1ItemData(base_item_id + 290),
    "Breaking Blocks: Minikit 2": LB1ItemData(base_item_id + 291),
    "Breaking Blocks: Minikit 3": LB1ItemData(base_item_id + 292),
    "Breaking Blocks: Minikit 4": LB1ItemData(base_item_id + 293),
    "Breaking Blocks: Minikit 5": LB1ItemData(base_item_id + 294),
    "Breaking Blocks: Minikit 6": LB1ItemData(base_item_id + 295),
    "Breaking Blocks: Minikit 7": LB1ItemData(base_item_id + 296),
    "Breaking Blocks: Minikit 8": LB1ItemData(base_item_id + 297),
    "Breaking Blocks: Minikit 9": LB1ItemData(base_item_id + 298),
    "Breaking Blocks: Minikit 10": LB1ItemData(base_item_id + 299),

    "Rockin' the Docks: Minikit 1": LB1ItemData(base_item_id + 300),
    "Rockin' the Docks: Minikit 2": LB1ItemData(base_item_id + 301),
    "Rockin' the Docks: Minikit 3": LB1ItemData(base_item_id + 302),
    "Rockin' the Docks: Minikit 4": LB1ItemData(base_item_id + 303),
    "Rockin' the Docks: Minikit 5": LB1ItemData(base_item_id + 304),
    "Rockin' the Docks: Minikit 6": LB1ItemData(base_item_id + 305),
    "Rockin' the Docks: Minikit 7": LB1ItemData(base_item_id + 306),
    "Rockin' the Docks: Minikit 8": LB1ItemData(base_item_id + 307),
    "Rockin' the Docks: Minikit 9": LB1ItemData(base_item_id + 308),
    "Rockin' the Docks: Minikit 10": LB1ItemData(base_item_id + 309),

    "Stealing the Show: Minikit 1": LB1ItemData(base_item_id + 310),
    "Stealing the Show: Minikit 2": LB1ItemData(base_item_id + 311),
    "Stealing the Show: Minikit 3": LB1ItemData(base_item_id + 312),
    "Stealing the Show: Minikit 4": LB1ItemData(base_item_id + 313),
    "Stealing the Show: Minikit 5": LB1ItemData(base_item_id + 314),
    "Stealing the Show: Minikit 6": LB1ItemData(base_item_id + 315),
    "Stealing the Show: Minikit 7": LB1ItemData(base_item_id + 316),
    "Stealing the Show: Minikit 8": LB1ItemData(base_item_id + 317),
    "Stealing the Show: Minikit 9": LB1ItemData(base_item_id + 318),
    "Stealing the Show: Minikit 10": LB1ItemData(base_item_id + 319),

    "Harbouring a Grudge: Minikit 1": LB1ItemData(base_item_id + 320),
    "Harbouring a Grudge: Minikit 2": LB1ItemData(base_item_id + 321),
    "Harbouring a Grudge: Minikit 3": LB1ItemData(base_item_id + 322),
    "Harbouring a Grudge: Minikit 4": LB1ItemData(base_item_id + 323),
    "Harbouring a Grudge: Minikit 5": LB1ItemData(base_item_id + 324),
    "Harbouring a Grudge: Minikit 6": LB1ItemData(base_item_id + 325),
    "Harbouring a Grudge: Minikit 7": LB1ItemData(base_item_id + 326),
    "Harbouring a Grudge: Minikit 8": LB1ItemData(base_item_id + 327),
    "Harbouring a Grudge: Minikit 9": LB1ItemData(base_item_id + 328),
    "Harbouring a Grudge: Minikit 10": LB1ItemData(base_item_id + 329),

    "A Daring Rescue: Minikit 1": LB1ItemData(base_item_id + 330),
    "A Daring Rescue: Minikit 2": LB1ItemData(base_item_id + 331),
    "A Daring Rescue: Minikit 3": LB1ItemData(base_item_id + 332),
    "A Daring Rescue: Minikit 4": LB1ItemData(base_item_id + 333),
    "A Daring Rescue: Minikit 5": LB1ItemData(base_item_id + 334),
    "A Daring Rescue: Minikit 6": LB1ItemData(base_item_id + 335),
    "A Daring Rescue: Minikit 7": LB1ItemData(base_item_id + 336),
    "A Daring Rescue: Minikit 8": LB1ItemData(base_item_id + 337),
    "A Daring Rescue: Minikit 9": LB1ItemData(base_item_id + 338),
    "A Daring Rescue: Minikit 10": LB1ItemData(base_item_id + 339),

    "Arctic World: Minikit 1": LB1ItemData(base_item_id + 340),
    "Arctic World: Minikit 2": LB1ItemData(base_item_id + 341),
    "Arctic World: Minikit 3": LB1ItemData(base_item_id + 342),
    "Arctic World: Minikit 4": LB1ItemData(base_item_id + 343),
    "Arctic World: Minikit 5": LB1ItemData(base_item_id + 344),
    "Arctic World: Minikit 6": LB1ItemData(base_item_id + 345),
    "Arctic World: Minikit 7": LB1ItemData(base_item_id + 346),
    "Arctic World: Minikit 8": LB1ItemData(base_item_id + 347),
    "Arctic World: Minikit 9": LB1ItemData(base_item_id + 348),
    "Arctic World: Minikit 10": LB1ItemData(base_item_id + 349),

    "A Surprise for the Commissioner: Minikit 1": LB1ItemData(base_item_id + 350),
    "A Surprise for the Commissioner: Minikit 2": LB1ItemData(base_item_id + 351),
    "A Surprise for the Commissioner: Minikit 3": LB1ItemData(base_item_id + 352),
    "A Surprise for the Commissioner: Minikit 4": LB1ItemData(base_item_id + 353),
    "A Surprise for the Commissioner: Minikit 5": LB1ItemData(base_item_id + 354),
    "A Surprise for the Commissioner: Minikit 6": LB1ItemData(base_item_id + 355),
    "A Surprise for the Commissioner: Minikit 7": LB1ItemData(base_item_id + 356),
    "A Surprise for the Commissioner: Minikit 8": LB1ItemData(base_item_id + 357),
    "A Surprise for the Commissioner: Minikit 9": LB1ItemData(base_item_id + 358),
    "A Surprise for the Commissioner: Minikit 10": LB1ItemData(base_item_id + 359),

    "Biplane Blast: Minikit 1": LB1ItemData(base_item_id + 360),
    "Biplane Blast: Minikit 2": LB1ItemData(base_item_id + 361),
    "Biplane Blast: Minikit 3": LB1ItemData(base_item_id + 362),
    "Biplane Blast: Minikit 4": LB1ItemData(base_item_id + 363),
    "Biplane Blast: Minikit 5": LB1ItemData(base_item_id + 364),
    "Biplane Blast: Minikit 6": LB1ItemData(base_item_id + 365),
    "Biplane Blast: Minikit 7": LB1ItemData(base_item_id + 366),
    "Biplane Blast: Minikit 8": LB1ItemData(base_item_id + 367),
    "Biplane Blast: Minikit 9": LB1ItemData(base_item_id + 368),
    "Biplane Blast: Minikit 10": LB1ItemData(base_item_id + 369),

    "The Joker's Masterpiece: Minikit 1": LB1ItemData(base_item_id + 370),
    "The Joker's Masterpiece: Minikit 2": LB1ItemData(base_item_id + 371),
    "The Joker's Masterpiece: Minikit 3": LB1ItemData(base_item_id + 372),
    "The Joker's Masterpiece: Minikit 4": LB1ItemData(base_item_id + 373),
    "The Joker's Masterpiece: Minikit 5": LB1ItemData(base_item_id + 374),
    "The Joker's Masterpiece: Minikit 6": LB1ItemData(base_item_id + 375),
    "The Joker's Masterpiece: Minikit 7": LB1ItemData(base_item_id + 376),
    "The Joker's Masterpiece: Minikit 8": LB1ItemData(base_item_id + 377),
    "The Joker's Masterpiece: Minikit 9": LB1ItemData(base_item_id + 378),
    "The Joker's Masterpiece: Minikit 10": LB1ItemData(base_item_id + 379),

    "The Lure of the Night: Minikit 1": LB1ItemData(base_item_id + 380),
    "The Lure of the Night: Minikit 2": LB1ItemData(base_item_id + 381),
    "The Lure of the Night: Minikit 3": LB1ItemData(base_item_id + 382),
    "The Lure of the Night: Minikit 4": LB1ItemData(base_item_id + 383),
    "The Lure of the Night: Minikit 5": LB1ItemData(base_item_id + 384),
    "The Lure of the Night: Minikit 6": LB1ItemData(base_item_id + 385),
    "The Lure of the Night: Minikit 7": LB1ItemData(base_item_id + 386),
    "The Lure of the Night: Minikit 8": LB1ItemData(base_item_id + 387),
    "The Lure of the Night: Minikit 9": LB1ItemData(base_item_id + 388),
    "The Lure of the Night: Minikit 10": LB1ItemData(base_item_id + 389),

    "Dying of Laughter: Minikit 1": LB1ItemData(base_item_id + 390),
    "Dying of Laughter: Minikit 2": LB1ItemData(base_item_id + 391),
    "Dying of Laughter: Minikit 3": LB1ItemData(base_item_id + 392),
    "Dying of Laughter: Minikit 4": LB1ItemData(base_item_id + 393),
    "Dying of Laughter: Minikit 5": LB1ItemData(base_item_id + 394),
    "Dying of Laughter: Minikit 6": LB1ItemData(base_item_id + 395),
    "Dying of Laughter: Minikit 7": LB1ItemData(base_item_id + 396),
    "Dying of Laughter: Minikit 8": LB1ItemData(base_item_id + 397),
    "Dying of Laughter: Minikit 9": LB1ItemData(base_item_id + 398),
    "Dying of Laughter: Minikit 10": LB1ItemData(base_item_id + 399),
}

hostage_item_table: Dict[str, LB1ItemData] = {
    "You Can Bank On Batman: Hostage": LB1ItemData(base_item_id + 400),
    "An Icy Reception: Hostage": LB1ItemData(base_item_id + 401),
    "A Poisonous Appointment: Hostage": LB1ItemData(base_item_id + 402),
    "The Face-Off: Hostage": LB1ItemData(base_item_id + 403),
    "There She Goes Again: Hostage": LB1ItemData(base_item_id + 404),
    "Under the City: Hostage": LB1ItemData(base_item_id + 405),
    "Zoo's Company: Hostage": LB1ItemData(base_item_id + 406),
    "Penguin's Lair: Hostage": LB1ItemData(base_item_id + 407),
    "Joker's Home Turf: Hostage": LB1ItemData(base_item_id + 408),
    "Little Fun at the Big Top: Hostage": LB1ItemData(base_item_id + 409),
    "In the Dark Night: Hostage": LB1ItemData(base_item_id + 410),
    "To the Top of the Tower: Hostage": LB1ItemData(base_item_id + 411),
    "The Riddler Makes a Withdrawal: Hostage": LB1ItemData(base_item_id + 412),
    "On the Rocks: Hostage": LB1ItemData(base_item_id + 413),
    "Green Fingers: Hostage": LB1ItemData(base_item_id + 414),
    "An Enterprising Theft: Hostage": LB1ItemData(base_item_id + 415),
    "Breaking Blocks: Hostage": LB1ItemData(base_item_id + 416),
    "Rockin' the Docks: Hostage": LB1ItemData(base_item_id + 417),
    "Stealing the Show: Hostage": LB1ItemData(base_item_id + 418),
    "A Daring Rescue: Hostage": LB1ItemData(base_item_id + 419),
    "Arctic World: Hostage": LB1ItemData(base_item_id + 420),
    "A Surprise for the Commissioner: Hostage": LB1ItemData(base_item_id + 421),
    "The Joker's Masterpiece: Hostage": LB1ItemData(base_item_id + 422),
    "The Lure of the Night: Hostage": LB1ItemData(base_item_id + 423),
    "Dying of Laughter: Hostage": LB1ItemData(base_item_id + 424),
}

level_unlocked_location_table: Dict[str, LB1ItemData] = {
    "You can Bank on Batman: Level Unlocked": LB1ItemData(base_item_id + 425, ItemClassification.progression),
    "An Icy Reception: Level Unlocked": LB1ItemData(base_item_id + 426, ItemClassification.progression),
    "Two-Face Chase: Level Unlocked": LB1ItemData(base_item_id + 427, ItemClassification.progression),
    "A Poisonous Appointment: Level Unlocked": LB1ItemData(base_item_id + 428, ItemClassification.progression),
    "The Face-Off: Level Unlocked": LB1ItemData(base_item_id + 429, ItemClassification.progression),
    "There She Goes Again: Level Unlocked": LB1ItemData(base_item_id + 430, ItemClassification.progression),
    "Batboat Battle: Level Unlocked": LB1ItemData(base_item_id + 431, ItemClassification.progression),
    "Under the City: Level Unlocked": LB1ItemData(base_item_id + 432, ItemClassification.progression),
    "Zoo's Company: Level Unlocked": LB1ItemData(base_item_id + 433, ItemClassification.progression),
    "Penguin's Lair: Level Unlocked": LB1ItemData(base_item_id + 434, ItemClassification.progression),
    "Joker's Home Turf: Level Unlocked": LB1ItemData(base_item_id + 435, ItemClassification.progression),
    "Little Fun at the Big Top: Level Unlocked": LB1ItemData(base_item_id + 436, ItemClassification.progression),
    "Flight of the Bat: Level Unlocked": LB1ItemData(base_item_id + 437, ItemClassification.progression),
    "In the Dark Night: Level Unlocked": LB1ItemData(base_item_id + 438, ItemClassification.progression),
    "To the Top of the Tower: Level Unlocked": LB1ItemData(base_item_id + 439, ItemClassification.progression),
    "The Riddler Makes a Withdrawal: Level Unlocked": LB1ItemData(base_item_id + 440, ItemClassification.progression),
    "On the Rocks: Level Unlocked": LB1ItemData(base_item_id + 441, ItemClassification.progression),
    "Green Fingers: Level Unlocked": LB1ItemData(base_item_id + 442, ItemClassification.progression),
    "An Enterprising Theft: Level Unlocked": LB1ItemData(base_item_id + 443, ItemClassification.progression),
    "Breaking Blocks: Level Unlocked": LB1ItemData(base_item_id + 444, ItemClassification.progression),
    "Rockin' the Docks: Level Unlocked": LB1ItemData(base_item_id + 445, ItemClassification.progression),
    "Stealing the Show: Level Unlocked": LB1ItemData(base_item_id + 446, ItemClassification.progression),
    "Harbouring a Grudge: Level Unlocked": LB1ItemData(base_item_id + 447, ItemClassification.progression),
    "A Daring Rescue: Level Unlocked": LB1ItemData(base_item_id + 448, ItemClassification.progression),
    "Arctic World: Level Unlocked": LB1ItemData(base_item_id + 449, ItemClassification.progression),
    "A Surprise for the Commissioner: Level Unlocked": LB1ItemData(base_item_id + 450, ItemClassification.progression),
    "Biplane Blast: Level Unlocked": LB1ItemData(base_item_id + 451, ItemClassification.progression),
    "The Joker's Masterpiece: Level Unlocked": LB1ItemData(base_item_id + 452, ItemClassification.progression),
    "The Lure of the Night: Level Unlocked": LB1ItemData(base_item_id + 453, ItemClassification.progression),
    "Dying of Laughter: Level Unlocked": LB1ItemData(base_item_id + 454, ItemClassification.progression),
}

item_data_table = {
    **minikit_item_table,
    **hostage_item_table,
    **level_unlocked_location_table
}

item_table = {name: data.code for name, data in item_data_table.items() if data.code is not None}
minikit_names_set = set(minikit_item_table.keys())

event_item_table: Dict[str, LB1ItemData] = {
    # "Completed Wayne Manor": LB1ItemData(None, classification=ItemClassification.progression),
    # "Completed Arkham Asylum": LB1ItemData(None, classification=ItemClassification.progression),
    # "Completed All Levels": LB1ItemData(None, classification=ItemClassification.progression),
    "Obtain Minikit Goal": LB1ItemData(None, classification=ItemClassification.progression),
    # "Hush": LB1ItemData(None, classification=ItemClassification.progression),
    # "Ra Sha Guul": LB1ItemData(None, classification=ItemClassification.progression),
}




