from BaseClasses import Location

class LB1Location(Location):
    game: str = "Lego Batman: The Videogame"


base_location_id: int = 400000

minikit_location_table: dict[str, int] = {
    "You can Bank on Batman: Minikit 1 - Inside the Garage near Spawn": base_location_id + 100,
    "You can Bank on Batman: Minikit 2 - Above the Garage near Spawn": base_location_id + 101,
    "You can Bank on Batman: Minikit 3 - Behind Glass Window near Spawn": base_location_id + 102,
    "You can Bank on Batman: Minikit 4 - Mind Control Behind Van in Toxic Waste": base_location_id + 103,
    "You can Bank on Batman: Minikit 5 - In the Sewer Grate": base_location_id + 104,
    "You can Bank on Batman: Minikit 6 - Behind a High Window by Cement Mixer": base_location_id + 105,
    "You can Bank on Batman: Minikit 7 - On a Balcony Behind Heavy Item near Downward Slope": base_location_id + 106,
    "You can Bank on Batman: Minikit 8 - From Using the Recycler": base_location_id + 107,
    "You can Bank on Batman: Minikit 9 - Park Two Cars": base_location_id + 108,
    "You can Bank on Batman: Minikit 10 - Destroy Five Phone Booths": base_location_id + 109,

    "An Icy Reception: Minikit 1 - On a Ledge near Spawn": base_location_id + 110,
    "An Icy Reception: Minikit 2 - Behind the Boarded Window on Ledge near Spawn": base_location_id + 111,
    "An Icy Reception: Minikit 3 - In the Silver Lego Icecream Stand": base_location_id + 112,
    "An Icy Reception: Minikit 4 - Behind the Icecream Truck": base_location_id + 113,
    "An Icy Reception: Minikit 5 - In the Alley with Hostage": base_location_id + 114,
    "An Icy Reception: Minikit 6 - In the Silver Legos Above Icecream Cones": base_location_id + 115,
    "An Icy Reception: Minikit 7 - In the Female Locked Room": base_location_id + 116,
    "An Icy Reception: Minikit 8 - In the Silver Legos Behind Toxic Gas": base_location_id + 117,
    "An Icy Reception: Minikit 9 - In the Vent with Fan": base_location_id + 118,
    "An Icy Reception: Minikit 10 - In the Hypnosis Room": base_location_id + 119,

    "Two-Face Chase: Minikit 1 - Destroy Three Dumpsters": base_location_id + 120,
    "Two-Face Chase: Minikit 2 - In the Manhole Cover": base_location_id + 121,
    "Two-Face Chase: Minikit 3 - Destroy the Southwest Trash Dumpster": base_location_id + 122,
    "Two-Face Chase: Minikit 4 - Destroy Three Cars": base_location_id + 123,
    "Two-Face Chase: Minikit 5 - Destroy the North Supports": base_location_id + 124,
    "Two-Face Chase: Minikit 6 - Destroy the South Supports": base_location_id + 125,
    "Two-Face Chase: Minikit 7 - Use Joker's Van Panel": base_location_id + 126,
    "Two-Face Chase: Minikit 8 - Use Harley's Truck Panel": base_location_id + 127,
    "Two-Face Chase: Minikit 9 - In the Telephone Booth": base_location_id + 128,
    "Two-Face Chase: Minikit 10 - Destroy Three Food Carts": base_location_id + 129,

    "A Poisonous Appointment: Minikit 1 - Destroy the Carrots": base_location_id + 130,
    "A Poisonous Appointment: Minikit 2 - On Top oft the Trees": base_location_id + 131,
    "A Poisonous Appointment: Minikit 3 - In the Heated Greenhouse": base_location_id + 132,
    "A Poisonous Appointment: Minikit 4 - Above the Orange Flowers": base_location_id + 133,
    "A Poisonous Appointment: Minikit 5 - Near the Rail above the Potted Plant": base_location_id + 134,
    "A Poisonous Appointment: Minikit 6 - In the Underwater Pipe": base_location_id + 135,
    "A Poisonous Appointment: Minikit 7 - In a Vat near the Second Pitcher Plant": base_location_id + 136,
    "A Poisonous Appointment: Minikit 8 - Destroy 3 Carrots": base_location_id + 137,
    "A Poisonous Appointment: Minikit 9 - Above the Heated Pipes": base_location_id + 138,
    "A Poisonous Appointment: Minikit 10 - In the Toxic Waste Room Above Ledge": base_location_id + 139,

    "The Face-Off: Minikit 1 - Jump on 5 Poles": base_location_id + 140,
    "The Face-Off: Minikit 2 - Above Grapple Point to the Right of Spawn": base_location_id + 141,
    "The Face-Off: Minikit 3 - Build the Dollar Sign": base_location_id + 142,
    "The Face-Off: Minikit 4 - In the Revolving Door": base_location_id + 143,
    "The Face-Off: Minikit 5 - On the Roof Above Recycler": base_location_id + 144,
    "The Face-Off: Minikit 6 - In the Toxic Waste Room Pipe": base_location_id + 145,
    "The Face-Off: Minikit 7 - Underneath the Toxic Waste near the Three Platform Bridge": base_location_id + 146,
    "The Face-Off: Minikit 8 - On the Right Side of Toxic Waste Room": base_location_id + 147,
    "The Face-Off: Minikit 9 - On the Right Side of Vault Room": base_location_id + 148,
    "The Face-Off: Minikit 10 - Destroy Five Chests": base_location_id + 149,

    "There She Goes Again: Minikit 1 - In the Female Locked Room": base_location_id + 150,
    "There She Goes Again: Minikit 2 - Drive the Car Into Garage": base_location_id + 151,
    "There She Goes Again: Minikit 3 - Locked Underwater Behind the Fence": base_location_id + 152,
    "There She Goes Again: Minikit 4 - Destroy Three Carrots": base_location_id + 153,
    "There She Goes Again: Minikit 5 - Locked Underwater by the Blue Pump": base_location_id + 154,
    "There She Goes Again: Minikit 6 - From Using the Lawnmower on the Flowers": base_location_id + 155,
    "There She Goes Again: Minikit 7 - Behind the Window Above Dumpster": base_location_id + 156,
    "There She Goes Again: Minikit 8 - Behind the Second Dumpster Under Water Tower": base_location_id + 157,
    "There She Goes Again: Minikit 9 - In the Glass Roof": base_location_id + 158,
    "There She Goes Again: Minikit 10 - In the Pipe After Breaking Glass": base_location_id + 159,

    "Batboat Battle: Minikit 1 - Turn on the Lighthouse": base_location_id + 160,
    "Batboat Battle: Minikit 2 - Blow Up the Silver Lego Box": base_location_id + 161,
    "Batboat Battle: Minikit 3 - Sink the Ship": base_location_id + 162,
    "Batboat Battle: Minikit 4 - Pull the Pipe": base_location_id + 163,
    "Batboat Battle: Minikit 5 - In Alcove Surrounded by Ice": base_location_id + 164,
    "Batboat Battle: Minikit 6 - In Silver Lego Crate Surrounded by Toxic Water": base_location_id + 165,
    "Batboat Battle: Minikit 7 - Destroy Silver Legos Around Pipe": base_location_id + 166,
    "Batboat Battle: Minikit 8 - Destroy Three Buoys": base_location_id + 167,
    "Batboat Battle: Minikit 9 - In the Corner Surrounded by Ice": base_location_id + 168,
    "Batboat Battle: Minikit 10 - Destroy Three Silver Lego Boxes in Toxic Water": base_location_id + 169,

    "Under the City: Minikit 1 - On Top of the Rafters": base_location_id + 170,
    "Under the City: Minikit 2 - In the Cage Behind Mind Control Door": base_location_id + 171,
    "Under the City: Minikit 3 - In the Glass Room": base_location_id + 172,
    "Under the City: Minikit 4 - On the Pipes Above the Robin Suit Swapper": base_location_id + 173,
    "Under the City: Minikit 5 - Destroy 5 Markers with the Boat Built from the Recycler": base_location_id + 174,
    "Under the City: Minikit 6 - Above the Ladder Across the Toxic Waste": base_location_id + 175,
    "Under the City: Minikit 7 - Jump From the Toilet": base_location_id + 176,
    "Under the City: Minikit 8 - Above the Scissor Lifter": base_location_id + 177,
    "Under the City: Minikit 9 - Underwater Underneath the Hatch": base_location_id + 178,
    "Under the City: Minikit 10 - On Top of the Pillar by the Generator": base_location_id + 179,

    "Zoo's Company: Minikit 1 - Hit Buoys with Boat in the Female Locked Room": base_location_id + 180,
    "Zoo's Company: Minikit 2 - In the Air on Other Side of Toxic Waste Behind the Barred Door": base_location_id + 181,
    "Zoo's Company: Minikit 3 - From Using the Recycler": base_location_id + 182,
    "Zoo's Company: Minikit 4 - Destroy the Silver Legos Above Recycler": base_location_id + 183,
    "Zoo's Company: Minikit 5 - In the Air After Building Totem": base_location_id + 184,
    "Zoo's Company: Minikit 6 - Destroy the Silver Legos in Lion Enclosure": base_location_id + 185,
    "Zoo's Company: Minikit 7 - In the Elephant Enclosure": base_location_id + 186,
    "Zoo's Company: Minikit 8 - Above the Lilypad by the Boat": base_location_id + 187,
    "Zoo's Company: Minikit 9 - On the Ledge Behind Waterfall": base_location_id + 188,
    "Zoo's Company: Minikit 10 - Behind the Strength Handle by Batman Suit Swapper": base_location_id + 189,

    "Penguin's Lair: Minikit 1 - Under the Glass Covered Water": base_location_id + 190,
    "Penguin's Lair: Minikit 2 - In the Silver Lego Cage": base_location_id + 191,
    "Penguin's Lair: Minikit 3 - On the Roof Above the Robin Suit Swapper": base_location_id + 192,
    "Penguin's Lair: Minikit 4 - From Growing 3 Carrots": base_location_id + 193,
    "Penguin's Lair: Minikit 5 - On the Icy Ledge": base_location_id + 194,
    "Penguin's Lair: Minikit 6 - On the Iceberg in the Final Battle Room": base_location_id + 195,
    "Penguin's Lair: Minikit 7 - On the South East Ledge in the Final Battle Room": base_location_id + 196,
    "Penguin's Lair: Minikit 8 - Behind the Silver Lego in Toxic Waste": base_location_id + 197,
    "Penguin's Lair: Minikit 9 - Destroy 4 Capacitors with Batarang": base_location_id + 198,
    "Penguin's Lair: Minikit 10 - From Building Heated Objects": base_location_id + 199,

    "Joker's Home Turf: Minikit 1 - Above the Fan Built from Silver Legos": base_location_id + 200,
    "Joker's Home Turf: Minikit 2 - From Cleaning up the Toxic Waste": base_location_id + 201,
    "Joker's Home Turf: Minikit 3 - From Completing the Puzzle Behind the Mind Control Door": base_location_id + 202,
    "Joker's Home Turf: Minikit 4 - Above the Ledge Accessed by Joker's Ladder": base_location_id + 203,
    "Joker's Home Turf: Minikit 5 - Caged in the Room Accessed by Controlling the Crane": base_location_id + 204,
    "Joker's Home Turf: Minikit 6 - In the Toxic Waste Pipe": base_location_id + 205,
    "Joker's Home Turf: Minikit 7 - High Up in Alcove Behind the Strength Gate": base_location_id + 206,
    "Joker's Home Turf: Minikit 8 - Crossing the Toxic Waste Water": base_location_id + 207,
    "Joker's Home Turf: Minikit 9 - In the Pool of Toxic Waste Drained by Generator": base_location_id + 208,
    "Joker's Home Turf: Minikit 10 - Behind the Silver Legos in Mad Hatter Fight": base_location_id + 209,

    "Little Fun at Big Top: Minikit 1 - Across the Tightrope Behind the Pushable Bus": base_location_id + 210,
    "Little Fun at Big Top: Minikit 2 - Carnival Target Game": base_location_id + 211,
    "Little Fun at Big Top: Minikit 3 - Inside the Water Filled Pipe Above Carnival Game": base_location_id + 212,
    "Little Fun at Big Top: Minikit 4 - Yellow Duck Carnival Game": base_location_id + 213,
    "Little Fun at Big Top: Minikit 5 - Behind the Window Above Gumball Machine": base_location_id + 214,
    "Little Fun at Big Top: Minikit 6 - From Activating the Teacup Ride": base_location_id + 215,
    "Little Fun at Big Top: Minikit 7 - On the Spiral Slide": base_location_id + 216,
    "Little Fun at Big Top: Minikit 8 - From Storing the Toy Boats": base_location_id + 217,
    "Little Fun at Big Top: Minikit 9 - Bumper Cars": base_location_id + 218,
    "Little Fun at Big Top: Minikit 10 - Tightrope on the Other Side of the Toxic Waste": base_location_id + 219,

    "Flight of the Bat: Minikit 1 - Destroy the 6 Missile Launchers": base_location_id + 220,
    "Flight of the Bat: Minikit 2 - Floating by 2 Turrets": base_location_id + 221,
    "Flight of the Bat: Minikit 3 - On the Railway": base_location_id + 222,
    "Flight of the Bat: Minikit 4 - In the Silver Lego by Hotel Sign": base_location_id + 223,
    "Flight of the Bat: Minikit 5 - Destroy the Gray Pipe": base_location_id + 224,
    "Flight of the Bat: Minikit 6 - From Blowing up the Silver Lego Valves": base_location_id + 225,
    "Flight of the Bat: Minikit 7 - Destroy 3 Gargoyles": base_location_id + 226,
    "Flight of the Bat: Minikit 8 - From Completing the Barrel Puzzle": base_location_id + 227,
    "Flight of the Bat: Minikit 9 - Platform near the Helicopter Pad": base_location_id + 228,
    "Flight of the Bat: Minikit 10 - Near the Yellow Barrels on the Rooftop": base_location_id + 229,

    "In the Dark Night: Minikit 1 - From Breaking the Glass Behind the Strength Door": base_location_id + 230,
    "In the Dark Night: Minikit 2 - Back Left Corner of the Rooftop Reached by Grapple": base_location_id + 231,
    "In the Dark Night: Minikit 3 - Destroy Objects to Find 3 Cakes": base_location_id + 232,
    "In the Dark Night: Minikit 4 - In the Fish Tank": base_location_id + 233,
    "In the Dark Night: Minikit 5 - From Flying the Helicopter into 10 Lights": base_location_id + 234,
    "In the Dark Night: Minikit 6 - In the Silver Lego Behind the Garbage Truck": base_location_id + 235,
    "In the Dark Night: Minikit 7 - On the Ledge Next to the Graffiti Wall": base_location_id + 236,
    "In the Dark Night: Minikit 8 - Inside the Silver Lego Manhole Cover": base_location_id + 237,
    "In the Dark Night: Minikit 9 - From Exploding the Generator in the Boss Room": base_location_id + 238,
    "In the Dark Night: Minikit 10 - In Glass Above Joker's Generator": base_location_id + 239,

    "To the Top of the Tower: Minikit 1 - Destroy 3 Silver Lego Gargoyles": base_location_id + 240,
    "To the Top of the Tower: Minikit 2 - Use the Buttons on the Ledge Above the Flowerbed": base_location_id + 241,
    "To the Top of the Tower: Minikit 3 - Behind the Glass Filled Arch": base_location_id + 242,
    "To the Top of the Tower: Minikit 4 - In the Destroyed Wall From Using the Recycler": base_location_id + 243,
    "To the Top of the Tower: Minikit 5 - Floating on the Right Side of the Cathedral": base_location_id + 244,
    "To the Top of the Tower: Minikit 6 - On the Wooden Platform Lowered by Generator": base_location_id + 245,
    "To the Top of the Tower: Minikit 7 - On the Ledge Above Magnet Wall": base_location_id + 246,
    "To the Top of the Tower: Minikit 8 - Hidden to the Right of the Lever": base_location_id + 247,
    "To the Top of the Tower: Minikit 9 - Use the Orane Buttons on Left Side of Bell Tower": base_location_id + 248,
    "To the Top of the Tower: Minikit 10 - In the Silver Lego Crate next to Statue Path": base_location_id + 249,

    "The Riddler Makes a Withdrawal: Minikit 1 - Behind the Garbage Truck": base_location_id + 250,
    "The Riddler Makes a Withdrawal: Minikit 2 - In the Air Above the Parking Lot": base_location_id + 251,
    "The Riddler Makes a Withdrawal: Minikit 3 - From Smashing the Blue Booth": base_location_id + 252,
    "The Riddler Makes a Withdrawal: Minikit 4 - Behind the Silver Lego Gate": base_location_id + 253,
    "The Riddler Makes a Withdrawal: Minikit 5 - Behind the Window Above the Grapple ": base_location_id + 254,
    "The Riddler Makes a Withdrawal: Minikit 6 - Inside the Glass House": base_location_id + 255,
    "The Riddler Makes a Withdrawal: Minikit 7 - Above the Rails Outside Bank": base_location_id + 256,
    "The Riddler Makes a Withdrawal: Minikit 8 - In the Barrels next to the Bank": base_location_id + 257,
    "The Riddler Makes a Withdrawal: Minikit 9 - Behind the Glass Window": base_location_id + 258,
    "The Riddler Makes a Withdrawal: Minikit 10 - In the Car Show Room": base_location_id + 259,

    "On the Rocks: Minikit 1 - Parking the Ice Cream Van": base_location_id + 260,
    "On the Rocks: Minikit 2 - Destroy 3 Snowmen": base_location_id + 261,
    "On the Rocks: Minikit 3 - Behind the Window near the Snowman Billboard": base_location_id + 262,
    "On the Rocks: Minikit 4 - Behind the Ice Wall": base_location_id + 263,
    "On the Rocks: Minikit 5 - On the Ledge Accessed by the Magnet Wall": base_location_id + 264,
    "On the Rocks: Minikit 6 - Floating below Rails off the Edge": base_location_id + 265,
    "On the Rocks: Minikit 7 - From Using the Recycler": base_location_id + 266,
    "On the Rocks: Minikit 8 - In the Silver Lego Crate by Hypnotised Man": base_location_id + 267,
    "On the Rocks: Minikit 9 - Above the Left Vat in the Last Fight": base_location_id + 268,
    "On the Rocks: Minikit 10 - Near Worker in the Last Fight": base_location_id + 269,

    "Green Fingers: Minikit 1 - Race Around the Track": base_location_id + 270,
    "Green Fingers: Minikit 2 - On the Wooden Platforms in the Garden": base_location_id + 271,
    "Green Fingers: Minikit 3 - Above the Rails On Left Side of the Building": base_location_id + 272,
    "Green Fingers: Minikit 4 - Complete the Block Puzzle": base_location_id + 273,
    "Green Fingers: Minikit 5 - In the Air After Turning on the Fountain": base_location_id + 274,
    "Green Fingers: Minikit 6 - Near the Pipe Above the Toxic Waste": base_location_id + 275,
    "Green Fingers: Minikit 7 - Break Machine Behind the Silver Lego Door": base_location_id + 276,
    "Green Fingers: Minikit 8 - In the Hole Above the Heated Pipe": base_location_id + 277,
    "Green Fingers: Minikit 9 - Floating Above the Water in the Other Water Tank": base_location_id + 278,
    "Green Fingers: Minikit 10 - In the Metal Cage Below the Hypnotized Man": base_location_id + 279,

    "An Enterprising Theft: Minikit 1 - Above the Display Case": base_location_id + 280,
    "An Enterprising Theft: Minikit 2 - From Completing the Car Maze": base_location_id + 281,
    "An Enterprising Theft: Minikit 3 - Inside the Elevator": base_location_id + 282,
    "An Enterprising Theft: Minikit 4 - Behind the Glass Window": base_location_id + 283,
    "An Enterprising Theft: Minikit 5 - Fly the Helicopter in the Toxic Waste Room": base_location_id + 284,
    "An Enterprising Theft: Minikit 6 - In the Metal Pipe that the Hypnotized Man Opens": base_location_id + 285,
    "An Enterprising Theft: Minikit 7 - Behind the Silver Lego Grate": base_location_id + 286,
    "An Enterprising Theft: Minikit 8 - From Putting the Weight on the Scale": base_location_id + 287,
    "An Enterprising Theft: Minikit 9 - Above the Heated Pipe of the Silver Lego Gate": base_location_id + 288,
    "An Enterprising Theft: Minikit 10 - Next to the Glowing Purple Vat": base_location_id + 289,

    "Breaking Blocks: Minikit 1 - On the Large Leaves": base_location_id + 290,
    "Breaking Blocks: Minikit 2 - Destroy 3 Security Cameras": base_location_id + 291,
    "Breaking Blocks: Minikit 3 - Behind the 3rd Painting": base_location_id + 292,
    "Breaking Blocks: Minikit 4 - On a Ledge Above the Recycler": base_location_id + 293,
    "Breaking Blocks: Minikit 5 - Behind the Bookcase": base_location_id + 294,
    "Breaking Blocks: Minikit 6 - In the Silver Lego Cage near Hostage": base_location_id + 295,
    "Breaking Blocks: Minikit 7 - Destroy 4 Golden Piggy Banks": base_location_id + 296,
    "Breaking Blocks: Minikit 8 - In the Silver Lego Cage near the Lasers": base_location_id + 297,
    "Breaking Blocks: Minikit 9 - Push the Metal Legos off the Edge": base_location_id + 298,
    "Breaking Blocks: Minikit 10 - Behind the Silver Lego Vault Door": base_location_id + 299,

    "Rockin' the Docks: Minikit 1 - On the Rails in the Hostage Room": base_location_id + 300,
    "Rockin' the Docks: Minikit 2 - Destroy 3 Carrots": base_location_id + 301,
    "Rockin' the Docks: Minikit 3 - Inside the Boat": base_location_id + 302,
    "Rockin' the Docks: Minikit 4 - Park the Trucks on the Buttons": base_location_id + 303,
    "Rockin' the Docks: Minikit 5 - On the Ledge reached from the Plant Ladder": base_location_id + 304,
    "Rockin' the Docks: Minikit 6 - Destroy 5 Water Cannons on Docks": base_location_id + 305,
    "Rockin' the Docks: Minikit 7 - Joker's Pirate Ship Race": base_location_id + 306,
    "Rockin' the Docks: Minikit 8 - Beneath the Lily Pads": base_location_id + 307,
    "Rockin' the Docks: Minikit 9 - Use the Recycler in the Female Locked Room": base_location_id + 308,
    "Rockin' the Docks: Minikit 10 - On the Narrow Ledge to the Left After Riding the Elevator": base_location_id + 309,

    "Stealing the Show: Minikit 1 - In the Room Behind the Boarded Up Windows": base_location_id + 310,
    "Stealing the Show: Minikit 2 - Destroy 3 Neon Signs": base_location_id + 311,
    "Stealing the Show: Minikit 3 - On the Roof Above the Wall Fans": base_location_id + 312,
    "Stealing the Show: Minikit 4 - Behind Glass Roof after Helicopter Fight": base_location_id + 313,
    "Stealing the Show: Minikit 5 - On the Balcony Near the Edge of the Screen": base_location_id + 314,
    "Stealing the Show: Minikit 6 - On the Roof Above the Magnetic Wall": base_location_id + 315,
    "Stealing the Show: Minikit 7 - Inside the Glass Display Case": base_location_id + 316,
    "Stealing the Show: Minikit 8 - Inside the Crate Next to the Dinosaurs": base_location_id + 317,
    "Stealing the Show: Minikit 9 - Caged Above the Catapults": base_location_id + 318,
    "Stealing the Show: Minikit 10 - On the Roof of the Museum Accessed by a Ladder Inside": base_location_id + 319,

    "Harbouring a Grudge: Minikit 1 - Inside the Toxic Waste Barrel": base_location_id + 320,
    "Harbouring a Grudge: Minikit 2 - Destroy 3 Mini Oil Rigs": base_location_id + 321,
    "Harbouring a Grudge: Minikit 3 - Behind Silver Lego Locked Gate": base_location_id + 322,
    "Harbouring a Grudge: Minikit 4 - Destroy 5 Buoys": base_location_id + 323,
    "Harbouring a Grudge: Minikit 5 - Destroy the Docked Boat": base_location_id + 324,
    "Harbouring a Grudge: Minikit 6 - Floating Off of the Ramp": base_location_id + 325,
    "Harbouring a Grudge: Minikit 7 - Inside the Police Boat in Toxic Water": base_location_id + 326,
    "Harbouring a Grudge: Minikit 8 - Inside the Orange Crane's Crate": base_location_id + 327,
    "Harbouring a Grudge: Minikit 9 - Inside the Barrel Floating in Toxic Waste": base_location_id + 328,
    "Harbouring a Grudge: Minikit 10 - Behind the Robin Wall": base_location_id + 329,

    "A Daring Rescue: Minikit 1 - In the Underground Path Accessed through Manhole Cover": base_location_id + 330,
    "A Daring Rescue: Minikit 2 - Build a Band": base_location_id + 331,
    "A Daring Rescue: Minikit 3 - Complete the Water Pressure Puzzle": base_location_id + 332,
    "A Daring Rescue: Minikit 4 - Destroy 5 TVs": base_location_id + 333,
    "A Daring Rescue: Minikit 5 - From Using the Recycler": base_location_id + 334,
    "A Daring Rescue: Minikit 6 - Park 3 Police Vehicles": base_location_id + 335,
    "A Daring Rescue: Minikit 7 - Up the Stairs after Pulling the Glass Locked Switch": base_location_id + 336,
    "A Daring Rescue: Minikit 8 - Left Toilet Stall": base_location_id + 337,
    "A Daring Rescue: Minikit 9 - In the Case Above Magnet Wall": base_location_id + 338,
    "A Daring Rescue: Minikit 10 - Locked in Final Room Holding Cell": base_location_id + 339,

    "Arctic World: Minikit 1 - Inside the Ice Cream Shop": base_location_id + 340,
    "Arctic World: Minikit 2 - On the Penguin Sign after Powering up the Generator": base_location_id + 341,
    "Arctic World: Minikit 3 - In the Cave Blocked by Glass": base_location_id + 342,
    "Arctic World: Minikit 4 - Slalom Skiing": base_location_id + 343,
    "Arctic World: Minikit 5 - The Shark's Minikit": base_location_id + 344,
    "Arctic World: Minikit 6 - Complete the 3 Button Puzzle": base_location_id + 345,
    "Arctic World: Minikit 7 - Slide Through the 5 Yellow Gates": base_location_id + 346,
    "Arctic World: Minikit 8 - In the Air Above the Silver Legos": base_location_id + 347,
    "Arctic World: Minikit 9 - Underwater in Final Room": base_location_id + 348,
    "Arctic World: Minikit 10 - In the Hanging Silver Cage": base_location_id + 349,

    "A Surprise for the Commissioner: Minikit 1 - On Ledge Left of Spawn": base_location_id + 350,
    "A Surprise for the Commissioner: Minikit 2 - Behind the Glass Window": base_location_id + 351,
    "A Surprise for the Commissioner: Minikit 3 - Freeze 3 Ice Cream Cones": base_location_id + 352,
    "A Surprise for the Commissioner: Minikit 4 - Inside the Vending Machine In Hostage Room": base_location_id + 353,
    "A Surprise for the Commissioner: Minikit 5 - Behind the Door Above the Grapple": base_location_id + 354,
    "A Surprise for the Commissioner: Minikit 6 - On the Roller Coaster Slope": base_location_id + 355,
    "A Surprise for the Commissioner: Minikit 7 - On the Ledge Above the Silver Lego Antenna": base_location_id + 356,
    "A Surprise for the Commissioner: Minikit 8 - Underwater in the Duck Pond": base_location_id + 357,
    "A Surprise for the Commissioner: Minikit 9 - Park 4 Trucks": base_location_id + 358,
    "A Surprise for the Commissioner: Minikit 10 - Bring Ice Cream Truck to Garage": base_location_id + 359,

    "Biplane Blast: Minikit 1 - Destroy 10 Brown Towers": base_location_id + 360,
    "Biplane Blast: Minikit 2 - In the Chapel Tower": base_location_id + 361,
    "Biplane Blast: Minikit 3 - Activate the Signal Tower": base_location_id + 362,
    "Biplane Blast: Minikit 4 - Shoot 3 Joker Balloons": base_location_id + 363,
    "Biplane Blast: Minikit 5 - Destroy 3 Cages from the Joker Shield": base_location_id + 364,
    "Biplane Blast: Minikit 6 - Inside the Silver Air Conditioner": base_location_id + 365,
    "Biplane Blast: Minikit 7 - On Other Side of the Scarecrow Billboard": base_location_id + 366,
    "Biplane Blast: Minikit 8 - Behind the Crane": base_location_id + 367,
    "Biplane Blast: Minikit 9 - Inside Silver Lego Tank": base_location_id + 368,
    "Biplane Blast: Minikit 10 - Inside Silver Lego Cage by Bat Symbol": base_location_id + 369,

    "The Joker's Masterpiece: Minikit 1 - Smash 3 Containers": base_location_id + 370,
    "The Joker's Masterpiece: Minikit 2 - Behind the Laser Grid": base_location_id + 371,
    "The Joker's Masterpiece: Minikit 3 - Drop the Statue off the Ledge": base_location_id + 372,
    "The Joker's Masterpiece: Minikit 4 - Open the Painting Behind the Pillars": base_location_id + 373,
    "The Joker's Masterpiece: Minikit 5 - In Glass Display Case in Gas Room": base_location_id + 374,
    "The Joker's Masterpiece: Minikit 6 - Behind Pushable Wall": base_location_id + 375,
    "The Joker's Masterpiece: Minikit 7 - Build the Joker's Face": base_location_id + 376,
    "The Joker's Masterpiece: Minikit 8 - In the Wooden Crate Dropped from Hypnotized Man": base_location_id + 377,
    "The Joker's Masterpiece: Minikit 9 - In the Vent": base_location_id + 378,
    "The Joker's Masterpiece: Minikit 10 - From using the Generator Twice": base_location_id + 379,

    "The Lure of the Night: Minikit 1 - Inside the Silver Lego Box Dropped by Hypnotized Man": base_location_id + 380,
    "The Lure of the Night: Minikit 2 - Build the Green ?": base_location_id + 381,
    "The Lure of the Night: Minikit 3 - Build and Connect the Battery": base_location_id + 382,
    "The Lure of the Night: Minikit 4 - Navigate the Boat around the Circuit": base_location_id + 383,
    "The Lure of the Night: Minikit 5 - Above the Magnet Wall": base_location_id + 384,
    "The Lure of the Night: Minikit 6 - Behind Silver Lego Door": base_location_id + 385,
    "The Lure of the Night: Minikit 7 - Destroy 5 Fire Hydrants": base_location_id + 386,
    "The Lure of the Night: Minikit 8 - Behind the Purple and Green Climbing Set in Playground": base_location_id + 387,
    "The Lure of the Night: Minikit 9 - Behind Silver Lego Vault Doors": base_location_id + 388,
    "The Lure of the Night: Minikit 10 - In the Underwater Glass Cage": base_location_id + 389,

    "Dying of Laughter: Minikit 1 - On the Tightrope above the Potted Plants": base_location_id + 390,
    "Dying of Laughter: Minikit 2 - Behind the Glass Window on the Wooden Platform": base_location_id + 391,
    "Dying of Laughter: Minikit 3 - From Inside the Altar": base_location_id + 392,
    "Dying of Laughter: Minikit 4 - Above the Ladder Built from Destroying Silver Legos": base_location_id + 393,
    "Dying of Laughter: Minikit 5 - Above the Magnet Wall after Second Double Button": base_location_id + 394,
    "Dying of Laughter: Minikit 6 - Inside the Wooden Box next to the Elevator": base_location_id + 395,
    "Dying of Laughter: Minikit 7 - On the Platform Across from the Wooden Box": base_location_id + 396,
    "Dying of Laughter: Minikit 8 - Build and Destroy the Ice Sculpture": base_location_id + 397,
    "Dying of Laughter: Minikit 9 - Ring the Left Bell": base_location_id + 398,
    "Dying of Laughter: Minikit 10 - Ringing Both Bells with the Turret": base_location_id + 399,
}

# hostage_location_table: dict[str, int] = {
    #"You can Bank on Batman: Hostage": base_location_id + 400,
    # "An Icy Reception: Hostage" base_location_id + 401,
    # "A Poisonous Appointment: Hostage", base_location_id + 402,
    # "The Face-Off: Hostage", base_location_id + 403,
    # "There She Goes Again: Hostage", base_location_id + 404,
    # "Under The City: Hostage", base_location_id + 405,
    # "Zoo's Company: Hostage", base_location_id + 406,
    # "Penguin's Lair: Hostage", base_location_id + 407,
    # "Joker's Home Turf: Hostage", base_location_id + 408,
    # "Little Fun at the Big Top: Hostage", base_location_id + 409,
    # "In the Dark Night: Hostage", base_location_id + 410,
    # "To the Top of the Tower: Hostage", base_location_id + 411,
    # "The Riddler Makes a Withdrawal: Hostage", base_location_id + 412,
    # "On the Rocks: Hostage", base_location_id + 413,
    # "Green Fingers: Hostage", base_location_id + 414,
    # "An Enterprising Theft: Hostage", base_location_id + 415,
    # "Breaking Blocks: Hostage", base_location_id + 416,
    # "Rockin' the Docks: Hostage", base_location_id + 417,
    # "Stealing the Show: Hostage", base_location_id + 418,
    # "A Daring Rescue: Hostage", base_location_id + 419,
    # "Arctic World: Hostage", base_location_id + 420,
    # "A Surprise for the Commissioner: Hostage", base_location_id + 421,
    # "The Joker's Masterpiece: Hostage", base_location_id + 422,
    # "The Lure of the Night: Hostage", base_location_id + 423,
    # "Dying of Laughter: Hostage", base_location_id + 424,
# }

location_table = {
    **minikit_location_table,
    # **hostage_location_table
}
