# Character Definitions
batman_unlocked = "Batman Unlocked"
robin_unlocked = "Robin Unlocked"
brucewayne_unlocked = "Bruce Wayne Unlocked"
alfred_unlocked = "Alfred Unlocked"
batgirl_unlocked = "Batgirl Unlocked"
nightwing_unlocked = "Nightwing Unlocked"
commissionergordon_unlocked = "Commissioner Gordon Unlocked"
policeofficer_unlocked = "Police Officer Unlocked"
fishmonger_unlocked = "Fishmonger Unlocked"
militarypoliceman_unlocked = "Military Policeman Unlocked"
securityguard_unlocked = "Security Guard Unlocked"
swat_unlocked = "S.W.A.T Unlocked"
scientist_unlocked = "Scientist Unlocked"
sailor_unlocked = "Sailor Unlocked"
policemarksman_unlocked = "Police Marksman Unlocked"
clayface_unlocked = "Clayface Unlocked"
mrfreeze_unlocked = "Mr. Freeze Unlocked"
poisonivy_unlocked = "Poison Ivy Unlocked"
twoface_unlocked = "Two-Face Unlocked"
riddler_unlocked = "The Riddler Unlocked"
bane_unlocked = "Bane Unlocked"
catwoman_unlocked = "Catwoman Unlocked"
catwomanclassic_unlocked = "Catwoman (Classic) Unlocked"
killercroc_unlocked = "Killer Croc Unlocked"
manbat_unlocked = "Man-Bat Unlocked"
penguin_unlocked = "The Penguin Unlocked"
harleyquinn_unlocked = "Harley Quinn Unlocked"
scarecrow_unlocked = "The Scarecrow Unlocked"
killermoth_unlocked = "Killer Moth Unlocked"
madhatter_unlocked = "Mad Hatter Unlocked"
joker_unlocked = "The Joker Unlocked"
jokertropical_unlocked = "The Joker (Tropical) Unlocked"
poisonivygoon_unlocked = "Poison Ivy Goon Unlocked"
zoosweeper_unlocked = "Zoo Sweeper Unlocked"
freezegirl_unlocked = "Freeze Girl Unlocked"
yeti_unlocked = "Yeti Unlocked"
riddlergoon_unlocked = "Riddler Goon Unlocked"
riddlerhenchman_unlocked = "Riddler Henchman Unlocked"
penguingoon_unlocked = "Penguin Goon Unlocked"
penguinhenchman_unlocked = "Penguin Henchman Unlocked"
penguinminion_unlocked = "Penguin Minion Unlocked"
jokergoon_unlocked = "Joker Goon Unlocked"
jokerhenchman_unlocked = "Joker Henchman Unlocked"
clowngoon_unlocked = "Clown Goon Unlocked"


# Hard Character Definitions
hush_unlocked = "Hush Unlocked"
rasalghul_unlocked = "Ra's al Ghul Unlocked"

# Automobile Definitions
batmobile_unlocked = "Batmobile Unlocked"
batcycle_unlocked = "Batcycle Unlocked"
policecar_unlocked = "Police Car Unlocked"
policebike_unlocked = "Police Bike Unlocked"
policevan_unlocked = "Police Van Unlocked"
battank_unlocked = "Bat-Tank Unlocked"
catmotorcycle_unlocked = "Catwoman's Motorcycle Unlocked"
armouredtruck_unlocked = "Two-Face's Armoured Truck Unlocked"
freezekart_unlocked = "Mr. Freeze's Kart Unlocked"
hammertruck_unlocked = "Harley Quinn's Hammer Truck Unlocked"
jokervan_unlocked = "The Joker's Van Unlocked"
garbagetruck_unlocked = "Garbage Truck Unlocked"

# Watercraft Definitions
batboat_unlocked = "Batboat Unlocked"
robinswatercraft_unlocked = "Robin's Watercraft Unlocked"
robinssubmarine_unlocked = "Robin's Submarine Unlocked"
policewatercraft_unlocked = "Police Watercraft Unlocked"
policeboat_unlocked = "Police Boat Unlocked"
penguinsubmarine_unlocked = "Penguin's Submarine Unlocked"
swamprider_unlocked = "Killer Croc's Swamp Rider Unlocked"
penguingoonsub_unlocked = "Penguin Goon Submarine Unlocked"
iceberg_unlocked = "Mr. Freeze's Iceberg Unlocked"
steamboat_unlocked = "Mad Hatter's Steamboat Unlocked"

# Aircraft Definitions
batwing_unlocked = "Batwing Unlocked"
batcopter_unlocked = "Batcopter Unlocked"
harbourhelicopter_unlocked = "Harbour Helicopter Unlocked"
policehelicopter_unlocked = "Police Helicopter Unlocked"
privatejet_unlocked = "Bruce Wayne's Private Jet Unlocked"
jokerhelicopter_unlocked = "The Joker's Helicopter Unlocked"
biplane_unlocked = "The Scarecrow's Biplane Unlocked"
goonhelicopter_unlocked = "Goon Helicopter Unlocked"
riddlerjet_unlocked = "Riddler's Jet Unlocked"
glider_unlocked = "Mad Hatter's Glider Unlocked"

# Suit Definitions
heatprotectsuit = "Heat Protection Suit Unlocked"
glidesuit = "Glide Suit Unlocked"
demosuit = "Demolition Suit Unlocked"
sonicsuit = "Sonic Suit Unlocked"
watersuit = "Water Suit Unlocked"
techsuit = "Technology Suit Unlocked"
magsuit = "Magnet Suit Unlocked"
attractsuit = "Attract Suit Unlocked"

# Minikit Definitions
ycbob_min = "You Can Bank on Batman Minikit"
ycbob_min2 = "You Can Bank on Batman Minikit x2"
ycbob_min5 = "You Can Bank on Batman Minikit x5"
ycbob_min10 = "You Can Bank on Batman Minikit x10"

air_min = "An Icy Reception Minikit"
air_min2 = "An Icy Reception Minikit x2"
air_min5 = "An Icy Reception Minikit x5"
air_min10 = "An Icy Reception Minikit x10"

tfc_min = "Two-Face Chase Minikit"
tfc_min2 = "Two-Face Chase Minikit x2"
tfc_min5 = "Two-Face Chase Minikit x5"
tfc_min10 = "Two-Face Chase Minikit x10"

apa_min = "A Poisonous Appointment Minikit"
apa_min2 = "A Poisonous Appointment Minikit x2"
apa_min5 = "A Poisonous Appointment Minikit x5"
apa_min10 = "A Poisonous Appointment Minikit x10"

tfo_min = "The Face-Off Minikit"
tfo_min2 = "The Face-Off Minikit x2"
tfo_min5 = "The Face-Off Minikit x5"
tfo_min10 = "The Face-Off Minikit x10"

tsga_min = "There She Goes Again Minikit"
tsga_min2 = "There She Goes Again Minikit x2"
tsga_min5 = "There She Goes Again Minikit x5"
tsga_min10 = "There She Goes Again Minikit x10"

bbb_min = "Batboat Battle Minikit"
bbb_min2 = "Batboat Battle Minikit x2"
bbb_min5 = "Batboat Battle Minikit x5"
bbb_min10 = "Batboat Battle Minikit x10"

utc_min = "Under the City Minikit"
utc_min2 = "Under the City Minikit x2"
utc_min5 = "Under the City Minikit x5"
utc_min10 = "Under the City Minikit x10"

zc_min = "Zoo's Company Minikit"
zc_min2 = "Zoo's Company Minikit x2"
zc_min5 = "Zoo's Company Minikit x5"
zc_min10 = "Zoo's Company Minikit x10"

pl_min = "Penguin's Lair Minikit"
pl_min2 = "Penguin's Lair Minikit x2"
pl_min5 = "Penguin's Lair Minikit x5"
pl_min10 = "Penguin's Lair Minikit x10"

jht_min = "Joker's Home Turf Minikit"
jht_min2 = "Joker's Home Turf Minikit x2"
jht_min5 = "Joker's Home Turf Minikit x5"
jht_min10 = "Joker's Home Turf Minikit x10"

lfabt_min = "Little Fun at the Big Top Minikit"
lfabt_min2 = "Little Fun at the Big Top Minikit x2"
lfabt_min5 = "Little Fun at the Big Top Minikit x5"
lfabt_min10 = "Little Fun at the Big Top Minikit x10"

fotb_min = "Flight of the Bat Minikit"
fotb_min2 = "Flight of the Bat Minikit x2"
fotb_min5 = "Flight of the Bat Minikit x5"
fotb_min10 = "Flight of the Bat Minikit x10"

itdn_min = "In the Dark Night Minikit"
itdn_min2 = "In the Dark Night Minikit x2"
itdn_min5 = "In the Dark Night Minikit x5"
itdn_min10 = "In the Dark Night Minikit x10"

tttot_min = "To the Top of the Tower Minikit"
tttot_min2 = "To the Top of the Tower Minikit x2"
tttot_min5 = "To the Top of the Tower Minikit x5"
tttot_min10 = "To the Top of the Tower Minikit x10"

trmaw_min = "The Riddler Makes a Withdrawal Minikit"
trmaw_min2 = "The Riddler Makes a Withdrawal Minikit x2"
trmaw_min5 = "The Riddler Makes a Withdrawal Minikit x5"
trmaw_min10 = "The Riddler Makes a Withdrawal Minikit x10"

otr_min = "On the Rocks Minikit"
otr_min2 = "On the Rocks Minikit x2"
otr_min5 = "On the Rocks Minikit x5"
otr_min10 = "On the Rocks Minikit x10"

gf_min = "Green Fingers Minikit"
gf_min2 = "Green Fingers Minikit x2"
gf_min5 = "Green Fingers Minikit x5"
gf_min10 = "Green Fingers Minikit x10"

aet_min = "An Enterprising Theft Minikit"
aet_min2 = "An Enterprising Theft Minikit x2"
aet_min5 = "An Enterprising Theft Minikit x5"
aet_min10 = "An Enterprising Theft Minikit x10"

bb_min = "Breaking Blocks Minikit"
bb_min2 = "Breaking Blocks Minikit x2"
bb_min5 = "Breaking Blocks Minikit x5"
bb_min10 = "Breaking Blocks Minikit x10"

rtd_min = "Rockin' the Docks Minikit"
rtd_min2 = "Rockin' the Docks Minikit x2"
rtd_min5 = "Rockin' the Docks Minikit x5"
rtd_min10 = "Rockin' the Docks Minikit x10"

sts_min = "Stealing the Show Minikit"
sts_min2 = "Stealing the Show Minikit x2"
sts_min5 = "Stealing the Show Minikit x5"
sts_min10 = "Stealing the Show Minikit x10"

hag_min = "Harbouring a Grudge Minikit"
hag_min2 = "Harbouring a Grudge Minikit x2"
hag_min5 = "Harbouring a Grudge Minikit x5"
hag_min10 = "Harbouring a Grudge Minikit x10"

adr_min = "A Daring Rescue Minikit"
adr_min2 = "A Daring Rescue Minikit x2"
adr_min5 = "A Daring Rescue Minikit x5"
adr_min10 = "A Daring Rescue Minikit x10"

aw_min = "Arctic World Minikit"
aw_min2 = "Arctic World Minikit x2"
aw_min5 = "Arctic World Minikit x5"
aw_min10 = "Arctic World Minikit x10"

asftc_min = "A Surprise for the Commissioner Minikit"
asftc_min2 = "A Surprise for the Commissioner Minikit x2"
asftc_min5 = "A Surprise for the Commissioner Minikit x5"
asftc_min10 = "A Surprise for the Commissioner Minikit x10"

bbpl_min = "Biplane Blast Minikit"
bbpl_min2 = "Biplane Blast Minikit x2"
bbpl_min5 = "Biplane Blast Minikit x5"
bbpl_min10 = "Biplane Blast Minikit x10"

tjm_min = "The Joker's Masterpiece Minikit"
tjm_min2 = "The Joker's Masterpiece Minikit x2"
tjm_min5 = "The Joker's Masterpiece Minikit x5"
tjm_min10 = "The Joker's Masterpiece Minikit x10"

tlotn_min = "The Lure of the Night Minikit"
tlotn_min2 = "The Lure of the Night Minikit x2"
tlotn_min5 = "The Lure of the Night Minikit x5"
tlotn_min10 = "The Lure of the Night Minikit x10"

dol_min = "Dying of Laughter Minikit"
dol_min2 = "Dying of Laughter Minikit x2"
dol_min5 = "Dying of Laughter Minikit x5"
dol_min10 = "Dying of Laughter Minikit x10"


# Hostage Definitions
ycbob_host = "You Can Bank On Batman: Hostage"
air_host = "An Icy Reception: Hostage"
apa_host = "A Poisonous Appointment: Hostage"
tfo_host = "The Face-Off: Hostage"
tsga_host = "There She Goes Again: Hostage"
utc_host = "Under the City: Hostage"
zc_host = "Zoo's Company: Hostage"
pl_host = "Penguin's Lair: Hostage"
jht_host = "Joker's Home Turf: Hostage"
lfabt_host = "Little Fun at the Big Top: Hostage"
itdn_host = "In the Dark Night: Hostage"
tttot_host = "To the Top of the Tower: Hostage"
trmaw_host = "The Riddler Makes a Withdrawal: Hostage"
otr_host = "On the Rocks: Hostage"
gf_host = "Green Fingers: Hostage"
aet_host = "An Enterprising Theft: Hostage"
bb_host = "Breaking Blocks: Hostage"
rtd_host = "Rockin' the Docks: Hostage"
sts_host = "Stealing the Show: Hostage"
adr_host = "A Daring Rescue: Hostage"
aw_host = "Arctic World: Hostage"
asftc_host = "A Surprise for the Commissioner: Hostage"
tjm_host = "The Joker's Masterpiece: Hostage"
tlotn_host = "The Lure of the Night: Hostage"
dol_host = "Dying of Laughter: Hostage"

# Level Unlocked Definitions
ycbob_lvl = "You can Bank on Batman: Level Unlocked"
air_lvl = "An Icy Reception: Level Unlocked"
tfc_lvl = "Two-Face Chase: Level Unlocked"
apa_lvl = "A Poisonous Appointment: Level Unlocked"
tfo_lvl = "The Face-Off: Level Unlocked"
tsga_lvl = "There She Goes Again: Level Unlocked"
bbb_lvl = "Batboat Battle: Level Unlocked"
utc_lvl = "Under the City: Level Unlocked"
zc_lvl = "Zoo's Company: Level Unlocked"
pl_lvl = "Penguin's Lair: Level Unlocked"
jht_lvl = "Joker's Home Turf: Level Unlocked"
lfabt_lvl = "Little Fun at the Big Top: Level Unlocked"
fotb_lvl = "Flight of the Bat: Level Unlocked"
itdn_lvl = "In the Dark Night: Level Unlocked"
tttot_lvl = "To the Top of the Tower: Level Unlocked"
trmaw_lvl = "The Riddler Makes a Withdrawal: Level Unlocked"
otr_lvl = "On the Rocks: Level Unlocked"
gf_lvl = "Green Fingers: Level Unlocked"
aet_lvl = "An Enterprising Theft: Level Unlocked"
bb_lvl = "Breaking Blocks: Level Unlocked"
rtd_lvl = "Rockin' the Docks: Level Unlocked"
sts_lvl = "Stealing the Show: Level Unlocked"
hag_lvl = "Harbouring a Grudge: Level Unlocked"
adr_lvl = "A Daring Rescue: Level Unlocked"
aw_lvl = "Arctic World: Level Unlocked"
asftc_lvl = "A Surprise for the Commissioner: Level Unlocked"
bbpl_lvl = "Biplane Blast: Level Unlocked"
tjm_lvl = "The Joker's Masterpiece: Level Unlocked"
tlotn_lvl = "The Lure of the Night: Level Unlocked"
dol_lvl = "Dying of Laughter: Level Unlocked"

# True Status Definitions
ycbob_ts = "You Can Bank On Batman: True Super Hero"
air_ts = "An Icy Reception: True Super Hero"
tfc_ts = "Two-Face Chase: True Super Hero"
apa_ts = "A Poisonous Appointment: True Super Hero"
tfo_ts = "The Face-Off: True Super Hero"
tsga_ts = "There She Goes Again: True Super Hero"
bbb_ts = "Batboat Battle: True Super Hero"
utc_ts = "Under the City: True Super Hero"
zc_ts = "Zoo's Company: True Super Hero"
pl_ts = "Penguin's Lair: True Super Hero"
jht_ts = "Joker's Home Turf: True Super Hero"
lfabt_ts = "Little Fun at the Big Top: True Super Hero"
fotb_ts = "Flight of the Bat: True Super Hero"
itdn_ts = "In the Dark Night: True Super Hero"
tttot_ts = "To the Top of the Tower: True Super Hero"
trmaw_ts = "The Riddler Makes a Withdrawal: True Super Hero"
otr_ts = "On the Rocks: True Super Hero"
gf_ts = "Green Fingers: True Super Hero"
aet_ts = "An Enterprising Theft: True Super Hero"
bb_ts = "Breaking Blocks: True Super Hero"
rtd_ts = "Rockin' the Docks: True Super Hero"
sts_ts = "Stealing the Show: True Super Hero"
hag_ts = "Harbouring a Grudge: True Super Hero"
adr_ts = "A Daring Rescue: True Super Hero"
aw_ts = "Arctic World: True Super Hero"
asftc_ts = "A Surprise for the Commissioner: True Super Hero"
bbpl_ts = "Biplane Blast: True Super Hero"
tjm_ts = "The Joker's Masterpiece: True Super Hero"
tlotn_ts = "The Lure of the Night: True Super Hero"
dol_ts = "Dying of Laughter: True Super Hero"

# Red Brick Unlocked Definitions
silhouettes = "Silhouettes Unlocked"
beepbeep = "Beep Beep Unlocked"
icerink = "Ice Rink Unlocked"
disguise = "Disguise Unlocked"
extratoggle = "Extra Toggle Unlocked"
scorex2 = "Score x2 Unlocked"
scorex4 = "Score x4 Unlocked"
scorex6 = "Score x6 Unlocked"
scorex8 = "Score x8 Unlocked"
scorex10 = "Score x10 Unlocked"
studmagnet = "Stud Magnet Unlocked"
charstuds = "Character Studs Unlocked"
minidetect = "Minikit Detector Unlocked"
powerdetect = "Power Brick Detector Unlocked"
alwaysscore = "Always Score Multiply Unlocked"
fastbuild = "Fast Build Unlocked"
immunefreeze = "Immune to Freeze Unlocked"
regenhearts = "Regenerate Hearts Unlocked"
extrahearts = "Extra Hearts Unlocked"
invincibility = "Invincibility Unlocked"
fastgrap = "Fast Grapple (All Suits) Unlocked"
fastbat = "Fast Batarangs (All Suits) Unlocked"
moretargets = "More Batarang Targets (All Suits) Unlocked"
flamingbat = "Flaming Batarang (Heat Protection Suit) Unlocked"
slam = "Slam (Glide Suit) Unlocked"
moredet = "More Detonators (Demolition Suit) Unlocked"
armourplating = "Armour Plating (Demolition Suit) Unlocked"
sonicpain = "Sonic Pain (Sonic Suit) Unlocked"
areaeffect = "Area Effect (Sonic Suit) Unlocked"
bats = "Bats (Sonic Suit) Unlocked"
freezebatarang = "Freeze Batarang (Water Suit) Unlocked"
decoy = "Decoy (Technology Suit) Unlocked"
fastwalk = "Fast Walk (Magnet Suit) Unlocked"
fasterpieces = "Faster Pieces (Attract Suit) Unlocked"
piecedetect = "Piece Detector (Attract Suit) Unlocked"

purp = "Purple Stud"
